// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package repositoriesmocks

import (
	"context"
	"portal-system/internal/domain"
	"portal-system/internal/models"

	mock "github.com/stretchr/testify/mock"
)

// NewAuditLogRepository creates a new instance of AuditLogRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewAuditLogRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *AuditLogRepository {
	mock := &AuditLogRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// AuditLogRepository is an autogenerated mock type for the AuditLogRepository type
type AuditLogRepository struct {
	mock.Mock
}

type AuditLogRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *AuditLogRepository) EXPECT() *AuditLogRepository_Expecter {
	return &AuditLogRepository_Expecter{mock: &_m.Mock}
}

// Create provides a mock function for the type AuditLogRepository
func (_mock *AuditLogRepository) Create(ctx context.Context, log *models.AuditLog) error {
	ret := _mock.Called(ctx, log)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *models.AuditLog) error); ok {
		r0 = returnFunc(ctx, log)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// AuditLogRepository_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type AuditLogRepository_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - log *models.AuditLog
func (_e *AuditLogRepository_Expecter) Create(ctx interface{}, log interface{}) *AuditLogRepository_Create_Call {
	return &AuditLogRepository_Create_Call{Call: _e.mock.On("Create", ctx, log)}
}

func (_c *AuditLogRepository_Create_Call) Run(run func(ctx context.Context, log *models.AuditLog)) *AuditLogRepository_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *models.AuditLog
		if args[1] != nil {
			arg1 = args[1].(*models.AuditLog)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *AuditLogRepository_Create_Call) Return(err error) *AuditLogRepository_Create_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *AuditLogRepository_Create_Call) RunAndReturn(run func(ctx context.Context, log *models.AuditLog) error) *AuditLogRepository_Create_Call {
	_c.Call.Return(run)
	return _c
}

// List provides a mock function for the type AuditLogRepository
func (_mock *AuditLogRepository) List(ctx context.Context, filter domain.AuditLogFilter) ([]models.AuditLog, int64, error) {
	ret := _mock.Called(ctx, filter)

	if len(ret) == 0 {
		panic("no return value specified for List")
	}

	var r0 []models.AuditLog
	var r1 int64
	var r2 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, domain.AuditLogFilter) ([]models.AuditLog, int64, error)); ok {
		return returnFunc(ctx, filter)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, domain.AuditLogFilter) []models.AuditLog); ok {
		r0 = returnFunc(ctx, filter)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]models.AuditLog)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, domain.AuditLogFilter) int64); ok {
		r1 = returnFunc(ctx, filter)
	} else {
		r1 = ret.Get(1).(int64)
	}
	if returnFunc, ok := ret.Get(2).(func(context.Context, domain.AuditLogFilter) error); ok {
		r2 = returnFunc(ctx, filter)
	} else {
		r2 = ret.Error(2)
	}
	return r0, r1, r2
}

// AuditLogRepository_List_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'List'
type AuditLogRepository_List_Call struct {
	*mock.Call
}

// List is a helper method to define mock.On call
//   - ctx context.Context
//   - filter domain.AuditLogFilter
func (_e *AuditLogRepository_Expecter) List(ctx interface{}, filter interface{}) *AuditLogRepository_List_Call {
	return &AuditLogRepository_List_Call{Call: _e.mock.On("List", ctx, filter)}
}

func (_c *AuditLogRepository_List_Call) Run(run func(ctx context.Context, filter domain.AuditLogFilter)) *AuditLogRepository_List_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 domain.AuditLogFilter
		if args[1] != nil {
			arg1 = args[1].(domain.AuditLogFilter)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *AuditLogRepository_List_Call) Return(auditLogs []models.AuditLog, n int64, err error) *AuditLogRepository_List_Call {
	_c.Call.Return(auditLogs, n, err)
	return _c
}

func (_c *AuditLogRepository_List_Call) RunAndReturn(run func(ctx context.Context, filter domain.AuditLogFilter) ([]models.AuditLog, int64, error)) *AuditLogRepository_List_Call {
	_c.Call.Return(run)
	return _c
}
