// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package repositoriesmocks

import (
	"context"
	"portal-system/internal/models"

	"github.com/google/uuid"
	mock "github.com/stretchr/testify/mock"
)

// NewAuthSessionRepository creates a new instance of AuthSessionRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewAuthSessionRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *AuthSessionRepository {
	mock := &AuthSessionRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// AuthSessionRepository is an autogenerated mock type for the AuthSessionRepository type
type AuthSessionRepository struct {
	mock.Mock
}

type AuthSessionRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *AuthSessionRepository) EXPECT() *AuthSessionRepository_Expecter {
	return &AuthSessionRepository_Expecter{mock: &_m.Mock}
}

// Create provides a mock function for the type AuthSessionRepository
func (_mock *AuthSessionRepository) Create(ctx context.Context, session *models.AuthSession) error {
	ret := _mock.Called(ctx, session)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *models.AuthSession) error); ok {
		r0 = returnFunc(ctx, session)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// AuthSessionRepository_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type AuthSessionRepository_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - session *models.AuthSession
func (_e *AuthSessionRepository_Expecter) Create(ctx interface{}, session interface{}) *AuthSessionRepository_Create_Call {
	return &AuthSessionRepository_Create_Call{Call: _e.mock.On("Create", ctx, session)}
}

func (_c *AuthSessionRepository_Create_Call) Run(run func(ctx context.Context, session *models.AuthSession)) *AuthSessionRepository_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *models.AuthSession
		if args[1] != nil {
			arg1 = args[1].(*models.AuthSession)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *AuthSessionRepository_Create_Call) Return(err error) *AuthSessionRepository_Create_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *AuthSessionRepository_Create_Call) RunAndReturn(run func(ctx context.Context, session *models.AuthSession) error) *AuthSessionRepository_Create_Call {
	_c.Call.Return(run)
	return _c
}

// FindActiveByID provides a mock function for the type AuthSessionRepository
func (_mock *AuthSessionRepository) FindActiveByID(ctx context.Context, id uuid.UUID) (*models.AuthSession, error) {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for FindActiveByID")
	}

	var r0 *models.AuthSession
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) (*models.AuthSession, error)); ok {
		return returnFunc(ctx, id)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) *models.AuthSession); ok {
		r0 = returnFunc(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.AuthSession)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = returnFunc(ctx, id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// AuthSessionRepository_FindActiveByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindActiveByID'
type AuthSessionRepository_FindActiveByID_Call struct {
	*mock.Call
}

// FindActiveByID is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
func (_e *AuthSessionRepository_Expecter) FindActiveByID(ctx interface{}, id interface{}) *AuthSessionRepository_FindActiveByID_Call {
	return &AuthSessionRepository_FindActiveByID_Call{Call: _e.mock.On("FindActiveByID", ctx, id)}
}

func (_c *AuthSessionRepository_FindActiveByID_Call) Run(run func(ctx context.Context, id uuid.UUID)) *AuthSessionRepository_FindActiveByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *AuthSessionRepository_FindActiveByID_Call) Return(authSession *models.AuthSession, err error) *AuthSessionRepository_FindActiveByID_Call {
	_c.Call.Return(authSession, err)
	return _c
}

func (_c *AuthSessionRepository_FindActiveByID_Call) RunAndReturn(run func(ctx context.Context, id uuid.UUID) (*models.AuthSession, error)) *AuthSessionRepository_FindActiveByID_Call {
	_c.Call.Return(run)
	return _c
}

// ListActiveByUserID provides a mock function for the type AuthSessionRepository
func (_mock *AuthSessionRepository) ListActiveByUserID(ctx context.Context, userID uuid.UUID) ([]models.AuthSession, error) {
	ret := _mock.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for ListActiveByUserID")
	}

	var r0 []models.AuthSession
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) ([]models.AuthSession, error)); ok {
		return returnFunc(ctx, userID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) []models.AuthSession); ok {
		r0 = returnFunc(ctx, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]models.AuthSession)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = returnFunc(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// AuthSessionRepository_ListActiveByUserID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListActiveByUserID'
type AuthSessionRepository_ListActiveByUserID_Call struct {
	*mock.Call
}

// ListActiveByUserID is a helper method to define mock.On call
//   - ctx context.Context
//   - userID uuid.UUID
func (_e *AuthSessionRepository_Expecter) ListActiveByUserID(ctx interface{}, userID interface{}) *AuthSessionRepository_ListActiveByUserID_Call {
	return &AuthSessionRepository_ListActiveByUserID_Call{Call: _e.mock.On("ListActiveByUserID", ctx, userID)}
}

func (_c *AuthSessionRepository_ListActiveByUserID_Call) Run(run func(ctx context.Context, userID uuid.UUID)) *AuthSessionRepository_ListActiveByUserID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *AuthSessionRepository_ListActiveByUserID_Call) Return(authSessions []models.AuthSession, err error) *AuthSessionRepository_ListActiveByUserID_Call {
	_c.Call.Return(authSessions, err)
	return _c
}

func (_c *AuthSessionRepository_ListActiveByUserID_Call) RunAndReturn(run func(ctx context.Context, userID uuid.UUID) ([]models.AuthSession, error)) *AuthSessionRepository_ListActiveByUserID_Call {
	_c.Call.Return(run)
	return _c
}

// RevokeAllByUserID provides a mock function for the type AuthSessionRepository
func (_mock *AuthSessionRepository) RevokeAllByUserID(ctx context.Context, userID uuid.UUID) error {
	ret := _mock.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for RevokeAllByUserID")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) error); ok {
		r0 = returnFunc(ctx, userID)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// AuthSessionRepository_RevokeAllByUserID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RevokeAllByUserID'
type AuthSessionRepository_RevokeAllByUserID_Call struct {
	*mock.Call
}

// RevokeAllByUserID is a helper method to define mock.On call
//   - ctx context.Context
//   - userID uuid.UUID
func (_e *AuthSessionRepository_Expecter) RevokeAllByUserID(ctx interface{}, userID interface{}) *AuthSessionRepository_RevokeAllByUserID_Call {
	return &AuthSessionRepository_RevokeAllByUserID_Call{Call: _e.mock.On("RevokeAllByUserID", ctx, userID)}
}

func (_c *AuthSessionRepository_RevokeAllByUserID_Call) Run(run func(ctx context.Context, userID uuid.UUID)) *AuthSessionRepository_RevokeAllByUserID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *AuthSessionRepository_RevokeAllByUserID_Call) Return(err error) *AuthSessionRepository_RevokeAllByUserID_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *AuthSessionRepository_RevokeAllByUserID_Call) RunAndReturn(run func(ctx context.Context, userID uuid.UUID) error) *AuthSessionRepository_RevokeAllByUserID_Call {
	_c.Call.Return(run)
	return _c
}

// RevokeByID provides a mock function for the type AuthSessionRepository
func (_mock *AuthSessionRepository) RevokeByID(ctx context.Context, sessionID uuid.UUID) error {
	ret := _mock.Called(ctx, sessionID)

	if len(ret) == 0 {
		panic("no return value specified for RevokeByID")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) error); ok {
		r0 = returnFunc(ctx, sessionID)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// AuthSessionRepository_RevokeByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RevokeByID'
type AuthSessionRepository_RevokeByID_Call struct {
	*mock.Call
}

// RevokeByID is a helper method to define mock.On call
//   - ctx context.Context
//   - sessionID uuid.UUID
func (_e *AuthSessionRepository_Expecter) RevokeByID(ctx interface{}, sessionID interface{}) *AuthSessionRepository_RevokeByID_Call {
	return &AuthSessionRepository_RevokeByID_Call{Call: _e.mock.On("RevokeByID", ctx, sessionID)}
}

func (_c *AuthSessionRepository_RevokeByID_Call) Run(run func(ctx context.Context, sessionID uuid.UUID)) *AuthSessionRepository_RevokeByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *AuthSessionRepository_RevokeByID_Call) Return(err error) *AuthSessionRepository_RevokeByID_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *AuthSessionRepository_RevokeByID_Call) RunAndReturn(run func(ctx context.Context, sessionID uuid.UUID) error) *AuthSessionRepository_RevokeByID_Call {
	_c.Call.Return(run)
	return _c
}
