// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package repositoriesmocks

import (
	"context"
	"portal-system/internal/models"

	"github.com/google/uuid"
	mock "github.com/stretchr/testify/mock"
)

// NewRefreshTokenRepository creates a new instance of RefreshTokenRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewRefreshTokenRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *RefreshTokenRepository {
	mock := &RefreshTokenRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// RefreshTokenRepository is an autogenerated mock type for the RefreshTokenRepository type
type RefreshTokenRepository struct {
	mock.Mock
}

type RefreshTokenRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *RefreshTokenRepository) EXPECT() *RefreshTokenRepository_Expecter {
	return &RefreshTokenRepository_Expecter{mock: &_m.Mock}
}

// Create provides a mock function for the type RefreshTokenRepository
func (_mock *RefreshTokenRepository) Create(ctx context.Context, token *models.RefreshToken) error {
	ret := _mock.Called(ctx, token)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *models.RefreshToken) error); ok {
		r0 = returnFunc(ctx, token)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// RefreshTokenRepository_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type RefreshTokenRepository_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - token *models.RefreshToken
func (_e *RefreshTokenRepository_Expecter) Create(ctx interface{}, token interface{}) *RefreshTokenRepository_Create_Call {
	return &RefreshTokenRepository_Create_Call{Call: _e.mock.On("Create", ctx, token)}
}

func (_c *RefreshTokenRepository_Create_Call) Run(run func(ctx context.Context, token *models.RefreshToken)) *RefreshTokenRepository_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *models.RefreshToken
		if args[1] != nil {
			arg1 = args[1].(*models.RefreshToken)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *RefreshTokenRepository_Create_Call) Return(err error) *RefreshTokenRepository_Create_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *RefreshTokenRepository_Create_Call) RunAndReturn(run func(ctx context.Context, token *models.RefreshToken) error) *RefreshTokenRepository_Create_Call {
	_c.Call.Return(run)
	return _c
}

// FindByTokenHash provides a mock function for the type RefreshTokenRepository
func (_mock *RefreshTokenRepository) FindByTokenHash(ctx context.Context, tokenHash string) (*models.RefreshToken, error) {
	ret := _mock.Called(ctx, tokenHash)

	if len(ret) == 0 {
		panic("no return value specified for FindByTokenHash")
	}

	var r0 *models.RefreshToken
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (*models.RefreshToken, error)); ok {
		return returnFunc(ctx, tokenHash)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) *models.RefreshToken); ok {
		r0 = returnFunc(ctx, tokenHash)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.RefreshToken)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, tokenHash)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// RefreshTokenRepository_FindByTokenHash_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindByTokenHash'
type RefreshTokenRepository_FindByTokenHash_Call struct {
	*mock.Call
}

// FindByTokenHash is a helper method to define mock.On call
//   - ctx context.Context
//   - tokenHash string
func (_e *RefreshTokenRepository_Expecter) FindByTokenHash(ctx interface{}, tokenHash interface{}) *RefreshTokenRepository_FindByTokenHash_Call {
	return &RefreshTokenRepository_FindByTokenHash_Call{Call: _e.mock.On("FindByTokenHash", ctx, tokenHash)}
}

func (_c *RefreshTokenRepository_FindByTokenHash_Call) Run(run func(ctx context.Context, tokenHash string)) *RefreshTokenRepository_FindByTokenHash_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *RefreshTokenRepository_FindByTokenHash_Call) Return(refreshToken *models.RefreshToken, err error) *RefreshTokenRepository_FindByTokenHash_Call {
	_c.Call.Return(refreshToken, err)
	return _c
}

func (_c *RefreshTokenRepository_FindByTokenHash_Call) RunAndReturn(run func(ctx context.Context, tokenHash string) (*models.RefreshToken, error)) *RefreshTokenRepository_FindByTokenHash_Call {
	_c.Call.Return(run)
	return _c
}

// MarkReplacement provides a mock function for the type RefreshTokenRepository
func (_mock *RefreshTokenRepository) MarkReplacement(ctx context.Context, id uuid.UUID, replacementID uuid.UUID) error {
	ret := _mock.Called(ctx, id, replacementID)

	if len(ret) == 0 {
		panic("no return value specified for MarkReplacement")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID) error); ok {
		r0 = returnFunc(ctx, id, replacementID)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// RefreshTokenRepository_MarkReplacement_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'MarkReplacement'
type RefreshTokenRepository_MarkReplacement_Call struct {
	*mock.Call
}

// MarkReplacement is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
//   - replacementID uuid.UUID
func (_e *RefreshTokenRepository_Expecter) MarkReplacement(ctx interface{}, id interface{}, replacementID interface{}) *RefreshTokenRepository_MarkReplacement_Call {
	return &RefreshTokenRepository_MarkReplacement_Call{Call: _e.mock.On("MarkReplacement", ctx, id, replacementID)}
}

func (_c *RefreshTokenRepository_MarkReplacement_Call) Run(run func(ctx context.Context, id uuid.UUID, replacementID uuid.UUID)) *RefreshTokenRepository_MarkReplacement_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		var arg2 uuid.UUID
		if args[2] != nil {
			arg2 = args[2].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *RefreshTokenRepository_MarkReplacement_Call) Return(err error) *RefreshTokenRepository_MarkReplacement_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *RefreshTokenRepository_MarkReplacement_Call) RunAndReturn(run func(ctx context.Context, id uuid.UUID, replacementID uuid.UUID) error) *RefreshTokenRepository_MarkReplacement_Call {
	_c.Call.Return(run)
	return _c
}

// RevokeByID provides a mock function for the type RefreshTokenRepository
func (_mock *RefreshTokenRepository) RevokeByID(ctx context.Context, id uuid.UUID) error {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for RevokeByID")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) error); ok {
		r0 = returnFunc(ctx, id)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// RefreshTokenRepository_RevokeByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RevokeByID'
type RefreshTokenRepository_RevokeByID_Call struct {
	*mock.Call
}

// RevokeByID is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
func (_e *RefreshTokenRepository_Expecter) RevokeByID(ctx interface{}, id interface{}) *RefreshTokenRepository_RevokeByID_Call {
	return &RefreshTokenRepository_RevokeByID_Call{Call: _e.mock.On("RevokeByID", ctx, id)}
}

func (_c *RefreshTokenRepository_RevokeByID_Call) Run(run func(ctx context.Context, id uuid.UUID)) *RefreshTokenRepository_RevokeByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *RefreshTokenRepository_RevokeByID_Call) Return(err error) *RefreshTokenRepository_RevokeByID_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *RefreshTokenRepository_RevokeByID_Call) RunAndReturn(run func(ctx context.Context, id uuid.UUID) error) *RefreshTokenRepository_RevokeByID_Call {
	_c.Call.Return(run)
	return _c
}

// RevokeBySessionID provides a mock function for the type RefreshTokenRepository
func (_mock *RefreshTokenRepository) RevokeBySessionID(ctx context.Context, sessionID uuid.UUID) error {
	ret := _mock.Called(ctx, sessionID)

	if len(ret) == 0 {
		panic("no return value specified for RevokeBySessionID")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) error); ok {
		r0 = returnFunc(ctx, sessionID)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// RefreshTokenRepository_RevokeBySessionID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RevokeBySessionID'
type RefreshTokenRepository_RevokeBySessionID_Call struct {
	*mock.Call
}

// RevokeBySessionID is a helper method to define mock.On call
//   - ctx context.Context
//   - sessionID uuid.UUID
func (_e *RefreshTokenRepository_Expecter) RevokeBySessionID(ctx interface{}, sessionID interface{}) *RefreshTokenRepository_RevokeBySessionID_Call {
	return &RefreshTokenRepository_RevokeBySessionID_Call{Call: _e.mock.On("RevokeBySessionID", ctx, sessionID)}
}

func (_c *RefreshTokenRepository_RevokeBySessionID_Call) Run(run func(ctx context.Context, sessionID uuid.UUID)) *RefreshTokenRepository_RevokeBySessionID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *RefreshTokenRepository_RevokeBySessionID_Call) Return(err error) *RefreshTokenRepository_RevokeBySessionID_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *RefreshTokenRepository_RevokeBySessionID_Call) RunAndReturn(run func(ctx context.Context, sessionID uuid.UUID) error) *RefreshTokenRepository_RevokeBySessionID_Call {
	_c.Call.Return(run)
	return _c
}

// RevokeByUserID provides a mock function for the type RefreshTokenRepository
func (_mock *RefreshTokenRepository) RevokeByUserID(ctx context.Context, userID uuid.UUID) error {
	ret := _mock.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for RevokeByUserID")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) error); ok {
		r0 = returnFunc(ctx, userID)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// RefreshTokenRepository_RevokeByUserID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RevokeByUserID'
type RefreshTokenRepository_RevokeByUserID_Call struct {
	*mock.Call
}

// RevokeByUserID is a helper method to define mock.On call
//   - ctx context.Context
//   - userID uuid.UUID
func (_e *RefreshTokenRepository_Expecter) RevokeByUserID(ctx interface{}, userID interface{}) *RefreshTokenRepository_RevokeByUserID_Call {
	return &RefreshTokenRepository_RevokeByUserID_Call{Call: _e.mock.On("RevokeByUserID", ctx, userID)}
}

func (_c *RefreshTokenRepository_RevokeByUserID_Call) Run(run func(ctx context.Context, userID uuid.UUID)) *RefreshTokenRepository_RevokeByUserID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *RefreshTokenRepository_RevokeByUserID_Call) Return(err error) *RefreshTokenRepository_RevokeByUserID_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *RefreshTokenRepository_RevokeByUserID_Call) RunAndReturn(run func(ctx context.Context, userID uuid.UUID) error) *RefreshTokenRepository_RevokeByUserID_Call {
	_c.Call.Return(run)
	return _c
}
