// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package repositoriesmocks

import (
	"context"
	"portal-system/internal/domain/constants"
	"portal-system/internal/models"

	"github.com/google/uuid"
	mock "github.com/stretchr/testify/mock"
)

// NewRoleRepository creates a new instance of RoleRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewRoleRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *RoleRepository {
	mock := &RoleRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// RoleRepository is an autogenerated mock type for the RoleRepository type
type RoleRepository struct {
	mock.Mock
}

type RoleRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *RoleRepository) EXPECT() *RoleRepository_Expecter {
	return &RoleRepository_Expecter{mock: &_m.Mock}
}

// AssignPermission provides a mock function for the type RoleRepository
func (_mock *RoleRepository) AssignPermission(ctx context.Context, roleID uuid.UUID, permID uuid.UUID) error {
	ret := _mock.Called(ctx, roleID, permID)

	if len(ret) == 0 {
		panic("no return value specified for AssignPermission")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID) error); ok {
		r0 = returnFunc(ctx, roleID, permID)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// RoleRepository_AssignPermission_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AssignPermission'
type RoleRepository_AssignPermission_Call struct {
	*mock.Call
}

// AssignPermission is a helper method to define mock.On call
//   - ctx context.Context
//   - roleID uuid.UUID
//   - permID uuid.UUID
func (_e *RoleRepository_Expecter) AssignPermission(ctx interface{}, roleID interface{}, permID interface{}) *RoleRepository_AssignPermission_Call {
	return &RoleRepository_AssignPermission_Call{Call: _e.mock.On("AssignPermission", ctx, roleID, permID)}
}

func (_c *RoleRepository_AssignPermission_Call) Run(run func(ctx context.Context, roleID uuid.UUID, permID uuid.UUID)) *RoleRepository_AssignPermission_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		var arg2 uuid.UUID
		if args[2] != nil {
			arg2 = args[2].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *RoleRepository_AssignPermission_Call) Return(err error) *RoleRepository_AssignPermission_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *RoleRepository_AssignPermission_Call) RunAndReturn(run func(ctx context.Context, roleID uuid.UUID, permID uuid.UUID) error) *RoleRepository_AssignPermission_Call {
	_c.Call.Return(run)
	return _c
}

// FindByCode provides a mock function for the type RoleRepository
func (_mock *RoleRepository) FindByCode(ctx context.Context, code constants.RoleCode) (*models.Role, error) {
	ret := _mock.Called(ctx, code)

	if len(ret) == 0 {
		panic("no return value specified for FindByCode")
	}

	var r0 *models.Role
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, constants.RoleCode) (*models.Role, error)); ok {
		return returnFunc(ctx, code)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, constants.RoleCode) *models.Role); ok {
		r0 = returnFunc(ctx, code)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.Role)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, constants.RoleCode) error); ok {
		r1 = returnFunc(ctx, code)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// RoleRepository_FindByCode_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindByCode'
type RoleRepository_FindByCode_Call struct {
	*mock.Call
}

// FindByCode is a helper method to define mock.On call
//   - ctx context.Context
//   - code constants.RoleCode
func (_e *RoleRepository_Expecter) FindByCode(ctx interface{}, code interface{}) *RoleRepository_FindByCode_Call {
	return &RoleRepository_FindByCode_Call{Call: _e.mock.On("FindByCode", ctx, code)}
}

func (_c *RoleRepository_FindByCode_Call) Run(run func(ctx context.Context, code constants.RoleCode)) *RoleRepository_FindByCode_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 constants.RoleCode
		if args[1] != nil {
			arg1 = args[1].(constants.RoleCode)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *RoleRepository_FindByCode_Call) Return(role *models.Role, err error) *RoleRepository_FindByCode_Call {
	_c.Call.Return(role, err)
	return _c
}

func (_c *RoleRepository_FindByCode_Call) RunAndReturn(run func(ctx context.Context, code constants.RoleCode) (*models.Role, error)) *RoleRepository_FindByCode_Call {
	_c.Call.Return(run)
	return _c
}

// FindByID provides a mock function for the type RoleRepository
func (_mock *RoleRepository) FindByID(ctx context.Context, id uuid.UUID) (*models.Role, error) {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for FindByID")
	}

	var r0 *models.Role
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) (*models.Role, error)); ok {
		return returnFunc(ctx, id)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) *models.Role); ok {
		r0 = returnFunc(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.Role)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = returnFunc(ctx, id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// RoleRepository_FindByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindByID'
type RoleRepository_FindByID_Call struct {
	*mock.Call
}

// FindByID is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
func (_e *RoleRepository_Expecter) FindByID(ctx interface{}, id interface{}) *RoleRepository_FindByID_Call {
	return &RoleRepository_FindByID_Call{Call: _e.mock.On("FindByID", ctx, id)}
}

func (_c *RoleRepository_FindByID_Call) Run(run func(ctx context.Context, id uuid.UUID)) *RoleRepository_FindByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *RoleRepository_FindByID_Call) Return(role *models.Role, err error) *RoleRepository_FindByID_Call {
	_c.Call.Return(role, err)
	return _c
}

func (_c *RoleRepository_FindByID_Call) RunAndReturn(run func(ctx context.Context, id uuid.UUID) (*models.Role, error)) *RoleRepository_FindByID_Call {
	_c.Call.Return(run)
	return _c
}

// GetWithPermissions provides a mock function for the type RoleRepository
func (_mock *RoleRepository) GetWithPermissions(ctx context.Context, roleID uuid.UUID) (*models.Role, error) {
	ret := _mock.Called(ctx, roleID)

	if len(ret) == 0 {
		panic("no return value specified for GetWithPermissions")
	}

	var r0 *models.Role
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) (*models.Role, error)); ok {
		return returnFunc(ctx, roleID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) *models.Role); ok {
		r0 = returnFunc(ctx, roleID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.Role)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = returnFunc(ctx, roleID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// RoleRepository_GetWithPermissions_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetWithPermissions'
type RoleRepository_GetWithPermissions_Call struct {
	*mock.Call
}

// GetWithPermissions is a helper method to define mock.On call
//   - ctx context.Context
//   - roleID uuid.UUID
func (_e *RoleRepository_Expecter) GetWithPermissions(ctx interface{}, roleID interface{}) *RoleRepository_GetWithPermissions_Call {
	return &RoleRepository_GetWithPermissions_Call{Call: _e.mock.On("GetWithPermissions", ctx, roleID)}
}

func (_c *RoleRepository_GetWithPermissions_Call) Run(run func(ctx context.Context, roleID uuid.UUID)) *RoleRepository_GetWithPermissions_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *RoleRepository_GetWithPermissions_Call) Return(role *models.Role, err error) *RoleRepository_GetWithPermissions_Call {
	_c.Call.Return(role, err)
	return _c
}

func (_c *RoleRepository_GetWithPermissions_Call) RunAndReturn(run func(ctx context.Context, roleID uuid.UUID) (*models.Role, error)) *RoleRepository_GetWithPermissions_Call {
	_c.Call.Return(run)
	return _c
}

// List provides a mock function for the type RoleRepository
func (_mock *RoleRepository) List(ctx context.Context) ([]models.Role, error) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for List")
	}

	var r0 []models.Role
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) ([]models.Role, error)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) []models.Role); ok {
		r0 = returnFunc(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]models.Role)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(ctx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// RoleRepository_List_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'List'
type RoleRepository_List_Call struct {
	*mock.Call
}

// List is a helper method to define mock.On call
//   - ctx context.Context
func (_e *RoleRepository_Expecter) List(ctx interface{}) *RoleRepository_List_Call {
	return &RoleRepository_List_Call{Call: _e.mock.On("List", ctx)}
}

func (_c *RoleRepository_List_Call) Run(run func(ctx context.Context)) *RoleRepository_List_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *RoleRepository_List_Call) Return(roles []models.Role, err error) *RoleRepository_List_Call {
	_c.Call.Return(roles, err)
	return _c
}

func (_c *RoleRepository_List_Call) RunAndReturn(run func(ctx context.Context) ([]models.Role, error)) *RoleRepository_List_Call {
	_c.Call.Return(run)
	return _c
}

// RemovePermission provides a mock function for the type RoleRepository
func (_mock *RoleRepository) RemovePermission(ctx context.Context, roleID uuid.UUID, permID uuid.UUID) error {
	ret := _mock.Called(ctx, roleID, permID)

	if len(ret) == 0 {
		panic("no return value specified for RemovePermission")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID) error); ok {
		r0 = returnFunc(ctx, roleID, permID)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// RoleRepository_RemovePermission_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RemovePermission'
type RoleRepository_RemovePermission_Call struct {
	*mock.Call
}

// RemovePermission is a helper method to define mock.On call
//   - ctx context.Context
//   - roleID uuid.UUID
//   - permID uuid.UUID
func (_e *RoleRepository_Expecter) RemovePermission(ctx interface{}, roleID interface{}, permID interface{}) *RoleRepository_RemovePermission_Call {
	return &RoleRepository_RemovePermission_Call{Call: _e.mock.On("RemovePermission", ctx, roleID, permID)}
}

func (_c *RoleRepository_RemovePermission_Call) Run(run func(ctx context.Context, roleID uuid.UUID, permID uuid.UUID)) *RoleRepository_RemovePermission_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		var arg2 uuid.UUID
		if args[2] != nil {
			arg2 = args[2].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *RoleRepository_RemovePermission_Call) Return(err error) *RoleRepository_RemovePermission_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *RoleRepository_RemovePermission_Call) RunAndReturn(run func(ctx context.Context, roleID uuid.UUID, permID uuid.UUID) error) *RoleRepository_RemovePermission_Call {
	_c.Call.Return(run)
	return _c
}
