// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package repositoriesmocks

import (
	"context"
	"portal-system/internal/domain/enum"
	"portal-system/internal/models"

	"github.com/google/uuid"
	mock "github.com/stretchr/testify/mock"
)

// NewUserTokenRepository creates a new instance of UserTokenRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewUserTokenRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *UserTokenRepository {
	mock := &UserTokenRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// UserTokenRepository is an autogenerated mock type for the UserTokenRepository type
type UserTokenRepository struct {
	mock.Mock
}

type UserTokenRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *UserTokenRepository) EXPECT() *UserTokenRepository_Expecter {
	return &UserTokenRepository_Expecter{mock: &_m.Mock}
}

// Create provides a mock function for the type UserTokenRepository
func (_mock *UserTokenRepository) Create(ctx context.Context, token *models.UserToken) error {
	ret := _mock.Called(ctx, token)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *models.UserToken) error); ok {
		r0 = returnFunc(ctx, token)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// UserTokenRepository_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type UserTokenRepository_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - token *models.UserToken
func (_e *UserTokenRepository_Expecter) Create(ctx interface{}, token interface{}) *UserTokenRepository_Create_Call {
	return &UserTokenRepository_Create_Call{Call: _e.mock.On("Create", ctx, token)}
}

func (_c *UserTokenRepository_Create_Call) Run(run func(ctx context.Context, token *models.UserToken)) *UserTokenRepository_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *models.UserToken
		if args[1] != nil {
			arg1 = args[1].(*models.UserToken)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *UserTokenRepository_Create_Call) Return(err error) *UserTokenRepository_Create_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *UserTokenRepository_Create_Call) RunAndReturn(run func(ctx context.Context, token *models.UserToken) error) *UserTokenRepository_Create_Call {
	_c.Call.Return(run)
	return _c
}

// FindValidToken provides a mock function for the type UserTokenRepository
func (_mock *UserTokenRepository) FindValidToken(ctx context.Context, tokenHash string, tokenType enum.TokenType) (*models.UserToken, error) {
	ret := _mock.Called(ctx, tokenHash, tokenType)

	if len(ret) == 0 {
		panic("no return value specified for FindValidToken")
	}

	var r0 *models.UserToken
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, enum.TokenType) (*models.UserToken, error)); ok {
		return returnFunc(ctx, tokenHash, tokenType)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, enum.TokenType) *models.UserToken); ok {
		r0 = returnFunc(ctx, tokenHash, tokenType)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.UserToken)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, enum.TokenType) error); ok {
		r1 = returnFunc(ctx, tokenHash, tokenType)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// UserTokenRepository_FindValidToken_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindValidToken'
type UserTokenRepository_FindValidToken_Call struct {
	*mock.Call
}

// FindValidToken is a helper method to define mock.On call
//   - ctx context.Context
//   - tokenHash string
//   - tokenType enum.TokenType
func (_e *UserTokenRepository_Expecter) FindValidToken(ctx interface{}, tokenHash interface{}, tokenType interface{}) *UserTokenRepository_FindValidToken_Call {
	return &UserTokenRepository_FindValidToken_Call{Call: _e.mock.On("FindValidToken", ctx, tokenHash, tokenType)}
}

func (_c *UserTokenRepository_FindValidToken_Call) Run(run func(ctx context.Context, tokenHash string, tokenType enum.TokenType)) *UserTokenRepository_FindValidToken_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 enum.TokenType
		if args[2] != nil {
			arg2 = args[2].(enum.TokenType)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *UserTokenRepository_FindValidToken_Call) Return(userToken *models.UserToken, err error) *UserTokenRepository_FindValidToken_Call {
	_c.Call.Return(userToken, err)
	return _c
}

func (_c *UserTokenRepository_FindValidToken_Call) RunAndReturn(run func(ctx context.Context, tokenHash string, tokenType enum.TokenType) (*models.UserToken, error)) *UserTokenRepository_FindValidToken_Call {
	_c.Call.Return(run)
	return _c
}

// MarkUsed provides a mock function for the type UserTokenRepository
func (_mock *UserTokenRepository) MarkUsed(ctx context.Context, id uuid.UUID) error {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for MarkUsed")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) error); ok {
		r0 = returnFunc(ctx, id)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// UserTokenRepository_MarkUsed_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'MarkUsed'
type UserTokenRepository_MarkUsed_Call struct {
	*mock.Call
}

// MarkUsed is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
func (_e *UserTokenRepository_Expecter) MarkUsed(ctx interface{}, id interface{}) *UserTokenRepository_MarkUsed_Call {
	return &UserTokenRepository_MarkUsed_Call{Call: _e.mock.On("MarkUsed", ctx, id)}
}

func (_c *UserTokenRepository_MarkUsed_Call) Run(run func(ctx context.Context, id uuid.UUID)) *UserTokenRepository_MarkUsed_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *UserTokenRepository_MarkUsed_Call) Return(err error) *UserTokenRepository_MarkUsed_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *UserTokenRepository_MarkUsed_Call) RunAndReturn(run func(ctx context.Context, id uuid.UUID) error) *UserTokenRepository_MarkUsed_Call {
	_c.Call.Return(run)
	return _c
}

// Revoke provides a mock function for the type UserTokenRepository
func (_mock *UserTokenRepository) Revoke(ctx context.Context, id uuid.UUID) error {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for Revoke")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) error); ok {
		r0 = returnFunc(ctx, id)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// UserTokenRepository_Revoke_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Revoke'
type UserTokenRepository_Revoke_Call struct {
	*mock.Call
}

// Revoke is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
func (_e *UserTokenRepository_Expecter) Revoke(ctx interface{}, id interface{}) *UserTokenRepository_Revoke_Call {
	return &UserTokenRepository_Revoke_Call{Call: _e.mock.On("Revoke", ctx, id)}
}

func (_c *UserTokenRepository_Revoke_Call) Run(run func(ctx context.Context, id uuid.UUID)) *UserTokenRepository_Revoke_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *UserTokenRepository_Revoke_Call) Return(err error) *UserTokenRepository_Revoke_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *UserTokenRepository_Revoke_Call) RunAndReturn(run func(ctx context.Context, id uuid.UUID) error) *UserTokenRepository_Revoke_Call {
	_c.Call.Return(run)
	return _c
}

// RevokeByUserAndType provides a mock function for the type UserTokenRepository
func (_mock *UserTokenRepository) RevokeByUserAndType(ctx context.Context, userID uuid.UUID, tokenType enum.TokenType) error {
	ret := _mock.Called(ctx, userID, tokenType)

	if len(ret) == 0 {
		panic("no return value specified for RevokeByUserAndType")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, enum.TokenType) error); ok {
		r0 = returnFunc(ctx, userID, tokenType)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// UserTokenRepository_RevokeByUserAndType_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RevokeByUserAndType'
type UserTokenRepository_RevokeByUserAndType_Call struct {
	*mock.Call
}

// RevokeByUserAndType is a helper method to define mock.On call
//   - ctx context.Context
//   - userID uuid.UUID
//   - tokenType enum.TokenType
func (_e *UserTokenRepository_Expecter) RevokeByUserAndType(ctx interface{}, userID interface{}, tokenType interface{}) *UserTokenRepository_RevokeByUserAndType_Call {
	return &UserTokenRepository_RevokeByUserAndType_Call{Call: _e.mock.On("RevokeByUserAndType", ctx, userID, tokenType)}
}

func (_c *UserTokenRepository_RevokeByUserAndType_Call) Run(run func(ctx context.Context, userID uuid.UUID, tokenType enum.TokenType)) *UserTokenRepository_RevokeByUserAndType_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		var arg2 enum.TokenType
		if args[2] != nil {
			arg2 = args[2].(enum.TokenType)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *UserTokenRepository_RevokeByUserAndType_Call) Return(err error) *UserTokenRepository_RevokeByUserAndType_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *UserTokenRepository_RevokeByUserAndType_Call) RunAndReturn(run func(ctx context.Context, userID uuid.UUID, tokenType enum.TokenType) error) *UserTokenRepository_RevokeByUserAndType_Call {
	_c.Call.Return(run)
	return _c
}
