// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package servicesmocks

import (
	"context"
	"portal-system/internal/domain"
	"portal-system/internal/domain/constants"
	"portal-system/internal/models"

	"github.com/google/uuid"
	mock "github.com/stretchr/testify/mock"
)

// NewAdminService creates a new instance of AdminService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewAdminService(t interface {
	mock.TestingT
	Cleanup(func())
}) *AdminService {
	mock := &AdminService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// AdminService is an autogenerated mock type for the AdminService type
type AdminService struct {
	mock.Mock
}

type AdminService_Expecter struct {
	mock *mock.Mock
}

func (_m *AdminService) EXPECT() *AdminService_Expecter {
	return &AdminService_Expecter{mock: &_m.Mock}
}

// CreateUser provides a mock function for the type AdminService
func (_mock *AdminService) CreateUser(ctx context.Context, meta *domain.AuditMeta, actor *domain.AuditUser, in domain.CreateUserInput) (*models.User, error) {
	ret := _mock.Called(ctx, meta, actor, in)

	if len(ret) == 0 {
		panic("no return value specified for CreateUser")
	}

	var r0 *models.User
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *domain.AuditMeta, *domain.AuditUser, domain.CreateUserInput) (*models.User, error)); ok {
		return returnFunc(ctx, meta, actor, in)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *domain.AuditMeta, *domain.AuditUser, domain.CreateUserInput) *models.User); ok {
		r0 = returnFunc(ctx, meta, actor, in)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.User)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *domain.AuditMeta, *domain.AuditUser, domain.CreateUserInput) error); ok {
		r1 = returnFunc(ctx, meta, actor, in)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// AdminService_CreateUser_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateUser'
type AdminService_CreateUser_Call struct {
	*mock.Call
}

// CreateUser is a helper method to define mock.On call
//   - ctx context.Context
//   - meta *domain.AuditMeta
//   - actor *domain.AuditUser
//   - in domain.CreateUserInput
func (_e *AdminService_Expecter) CreateUser(ctx interface{}, meta interface{}, actor interface{}, in interface{}) *AdminService_CreateUser_Call {
	return &AdminService_CreateUser_Call{Call: _e.mock.On("CreateUser", ctx, meta, actor, in)}
}

func (_c *AdminService_CreateUser_Call) Run(run func(ctx context.Context, meta *domain.AuditMeta, actor *domain.AuditUser, in domain.CreateUserInput)) *AdminService_CreateUser_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *domain.AuditMeta
		if args[1] != nil {
			arg1 = args[1].(*domain.AuditMeta)
		}
		var arg2 *domain.AuditUser
		if args[2] != nil {
			arg2 = args[2].(*domain.AuditUser)
		}
		var arg3 domain.CreateUserInput
		if args[3] != nil {
			arg3 = args[3].(domain.CreateUserInput)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *AdminService_CreateUser_Call) Return(user *models.User, err error) *AdminService_CreateUser_Call {
	_c.Call.Return(user, err)
	return _c
}

func (_c *AdminService_CreateUser_Call) RunAndReturn(run func(ctx context.Context, meta *domain.AuditMeta, actor *domain.AuditUser, in domain.CreateUserInput) (*models.User, error)) *AdminService_CreateUser_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteUser provides a mock function for the type AdminService
func (_mock *AdminService) DeleteUser(ctx context.Context, meta *domain.AuditMeta, actor *domain.AuditUser, userID uuid.UUID) (*models.User, error) {
	ret := _mock.Called(ctx, meta, actor, userID)

	if len(ret) == 0 {
		panic("no return value specified for DeleteUser")
	}

	var r0 *models.User
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *domain.AuditMeta, *domain.AuditUser, uuid.UUID) (*models.User, error)); ok {
		return returnFunc(ctx, meta, actor, userID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *domain.AuditMeta, *domain.AuditUser, uuid.UUID) *models.User); ok {
		r0 = returnFunc(ctx, meta, actor, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.User)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *domain.AuditMeta, *domain.AuditUser, uuid.UUID) error); ok {
		r1 = returnFunc(ctx, meta, actor, userID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// AdminService_DeleteUser_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteUser'
type AdminService_DeleteUser_Call struct {
	*mock.Call
}

// DeleteUser is a helper method to define mock.On call
//   - ctx context.Context
//   - meta *domain.AuditMeta
//   - actor *domain.AuditUser
//   - userID uuid.UUID
func (_e *AdminService_Expecter) DeleteUser(ctx interface{}, meta interface{}, actor interface{}, userID interface{}) *AdminService_DeleteUser_Call {
	return &AdminService_DeleteUser_Call{Call: _e.mock.On("DeleteUser", ctx, meta, actor, userID)}
}

func (_c *AdminService_DeleteUser_Call) Run(run func(ctx context.Context, meta *domain.AuditMeta, actor *domain.AuditUser, userID uuid.UUID)) *AdminService_DeleteUser_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *domain.AuditMeta
		if args[1] != nil {
			arg1 = args[1].(*domain.AuditMeta)
		}
		var arg2 *domain.AuditUser
		if args[2] != nil {
			arg2 = args[2].(*domain.AuditUser)
		}
		var arg3 uuid.UUID
		if args[3] != nil {
			arg3 = args[3].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *AdminService_DeleteUser_Call) Return(user *models.User, err error) *AdminService_DeleteUser_Call {
	_c.Call.Return(user, err)
	return _c
}

func (_c *AdminService_DeleteUser_Call) RunAndReturn(run func(ctx context.Context, meta *domain.AuditMeta, actor *domain.AuditUser, userID uuid.UUID) (*models.User, error)) *AdminService_DeleteUser_Call {
	_c.Call.Return(run)
	return _c
}

// ListUsers provides a mock function for the type AdminService
func (_mock *AdminService) ListUsers(ctx context.Context, meta *domain.AuditMeta, actor *domain.AuditUser, in domain.UsersFilter) (*domain.ListUsersResult, error) {
	ret := _mock.Called(ctx, meta, actor, in)

	if len(ret) == 0 {
		panic("no return value specified for ListUsers")
	}

	var r0 *domain.ListUsersResult
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *domain.AuditMeta, *domain.AuditUser, domain.UsersFilter) (*domain.ListUsersResult, error)); ok {
		return returnFunc(ctx, meta, actor, in)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *domain.AuditMeta, *domain.AuditUser, domain.UsersFilter) *domain.ListUsersResult); ok {
		r0 = returnFunc(ctx, meta, actor, in)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.ListUsersResult)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *domain.AuditMeta, *domain.AuditUser, domain.UsersFilter) error); ok {
		r1 = returnFunc(ctx, meta, actor, in)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// AdminService_ListUsers_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListUsers'
type AdminService_ListUsers_Call struct {
	*mock.Call
}

// ListUsers is a helper method to define mock.On call
//   - ctx context.Context
//   - meta *domain.AuditMeta
//   - actor *domain.AuditUser
//   - in domain.UsersFilter
func (_e *AdminService_Expecter) ListUsers(ctx interface{}, meta interface{}, actor interface{}, in interface{}) *AdminService_ListUsers_Call {
	return &AdminService_ListUsers_Call{Call: _e.mock.On("ListUsers", ctx, meta, actor, in)}
}

func (_c *AdminService_ListUsers_Call) Run(run func(ctx context.Context, meta *domain.AuditMeta, actor *domain.AuditUser, in domain.UsersFilter)) *AdminService_ListUsers_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *domain.AuditMeta
		if args[1] != nil {
			arg1 = args[1].(*domain.AuditMeta)
		}
		var arg2 *domain.AuditUser
		if args[2] != nil {
			arg2 = args[2].(*domain.AuditUser)
		}
		var arg3 domain.UsersFilter
		if args[3] != nil {
			arg3 = args[3].(domain.UsersFilter)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *AdminService_ListUsers_Call) Return(listUsersResult *domain.ListUsersResult, err error) *AdminService_ListUsers_Call {
	_c.Call.Return(listUsersResult, err)
	return _c
}

func (_c *AdminService_ListUsers_Call) RunAndReturn(run func(ctx context.Context, meta *domain.AuditMeta, actor *domain.AuditUser, in domain.UsersFilter) (*domain.ListUsersResult, error)) *AdminService_ListUsers_Call {
	_c.Call.Return(run)
	return _c
}

// RestoreUser provides a mock function for the type AdminService
func (_mock *AdminService) RestoreUser(ctx context.Context, meta *domain.AuditMeta, actor *domain.AuditUser, userID uuid.UUID) (*models.User, error) {
	ret := _mock.Called(ctx, meta, actor, userID)

	if len(ret) == 0 {
		panic("no return value specified for RestoreUser")
	}

	var r0 *models.User
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *domain.AuditMeta, *domain.AuditUser, uuid.UUID) (*models.User, error)); ok {
		return returnFunc(ctx, meta, actor, userID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *domain.AuditMeta, *domain.AuditUser, uuid.UUID) *models.User); ok {
		r0 = returnFunc(ctx, meta, actor, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.User)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *domain.AuditMeta, *domain.AuditUser, uuid.UUID) error); ok {
		r1 = returnFunc(ctx, meta, actor, userID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// AdminService_RestoreUser_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RestoreUser'
type AdminService_RestoreUser_Call struct {
	*mock.Call
}

// RestoreUser is a helper method to define mock.On call
//   - ctx context.Context
//   - meta *domain.AuditMeta
//   - actor *domain.AuditUser
//   - userID uuid.UUID
func (_e *AdminService_Expecter) RestoreUser(ctx interface{}, meta interface{}, actor interface{}, userID interface{}) *AdminService_RestoreUser_Call {
	return &AdminService_RestoreUser_Call{Call: _e.mock.On("RestoreUser", ctx, meta, actor, userID)}
}

func (_c *AdminService_RestoreUser_Call) Run(run func(ctx context.Context, meta *domain.AuditMeta, actor *domain.AuditUser, userID uuid.UUID)) *AdminService_RestoreUser_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *domain.AuditMeta
		if args[1] != nil {
			arg1 = args[1].(*domain.AuditMeta)
		}
		var arg2 *domain.AuditUser
		if args[2] != nil {
			arg2 = args[2].(*domain.AuditUser)
		}
		var arg3 uuid.UUID
		if args[3] != nil {
			arg3 = args[3].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *AdminService_RestoreUser_Call) Return(user *models.User, err error) *AdminService_RestoreUser_Call {
	_c.Call.Return(user, err)
	return _c
}

func (_c *AdminService_RestoreUser_Call) RunAndReturn(run func(ctx context.Context, meta *domain.AuditMeta, actor *domain.AuditUser, userID uuid.UUID) (*models.User, error)) *AdminService_RestoreUser_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateRole provides a mock function for the type AdminService
func (_mock *AdminService) UpdateRole(ctx context.Context, meta *domain.AuditMeta, actor *domain.AuditUser, id uuid.UUID, roleCode constants.RoleCode) (*models.User, error) {
	ret := _mock.Called(ctx, meta, actor, id, roleCode)

	if len(ret) == 0 {
		panic("no return value specified for UpdateRole")
	}

	var r0 *models.User
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *domain.AuditMeta, *domain.AuditUser, uuid.UUID, constants.RoleCode) (*models.User, error)); ok {
		return returnFunc(ctx, meta, actor, id, roleCode)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *domain.AuditMeta, *domain.AuditUser, uuid.UUID, constants.RoleCode) *models.User); ok {
		r0 = returnFunc(ctx, meta, actor, id, roleCode)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.User)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *domain.AuditMeta, *domain.AuditUser, uuid.UUID, constants.RoleCode) error); ok {
		r1 = returnFunc(ctx, meta, actor, id, roleCode)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// AdminService_UpdateRole_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateRole'
type AdminService_UpdateRole_Call struct {
	*mock.Call
}

// UpdateRole is a helper method to define mock.On call
//   - ctx context.Context
//   - meta *domain.AuditMeta
//   - actor *domain.AuditUser
//   - id uuid.UUID
//   - roleCode constants.RoleCode
func (_e *AdminService_Expecter) UpdateRole(ctx interface{}, meta interface{}, actor interface{}, id interface{}, roleCode interface{}) *AdminService_UpdateRole_Call {
	return &AdminService_UpdateRole_Call{Call: _e.mock.On("UpdateRole", ctx, meta, actor, id, roleCode)}
}

func (_c *AdminService_UpdateRole_Call) Run(run func(ctx context.Context, meta *domain.AuditMeta, actor *domain.AuditUser, id uuid.UUID, roleCode constants.RoleCode)) *AdminService_UpdateRole_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *domain.AuditMeta
		if args[1] != nil {
			arg1 = args[1].(*domain.AuditMeta)
		}
		var arg2 *domain.AuditUser
		if args[2] != nil {
			arg2 = args[2].(*domain.AuditUser)
		}
		var arg3 uuid.UUID
		if args[3] != nil {
			arg3 = args[3].(uuid.UUID)
		}
		var arg4 constants.RoleCode
		if args[4] != nil {
			arg4 = args[4].(constants.RoleCode)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
			arg4,
		)
	})
	return _c
}

func (_c *AdminService_UpdateRole_Call) Return(user *models.User, err error) *AdminService_UpdateRole_Call {
	_c.Call.Return(user, err)
	return _c
}

func (_c *AdminService_UpdateRole_Call) RunAndReturn(run func(ctx context.Context, meta *domain.AuditMeta, actor *domain.AuditUser, id uuid.UUID, roleCode constants.RoleCode) (*models.User, error)) *AdminService_UpdateRole_Call {
	_c.Call.Return(run)
	return _c
}
