// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package servicesmocks

import (
	"context"
	"portal-system/internal/domain"
	"portal-system/internal/domain/enum"

	mock "github.com/stretchr/testify/mock"
)

// NewAuditLogger creates a new instance of AuditLogger. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewAuditLogger(t interface {
	mock.TestingT
	Cleanup(func())
}) *AuditLogger {
	mock := &AuditLogger{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// AuditLogger is an autogenerated mock type for the AuditLogger type
type AuditLogger struct {
	mock.Mock
}

type AuditLogger_Expecter struct {
	mock *mock.Mock
}

func (_m *AuditLogger) EXPECT() *AuditLogger_Expecter {
	return &AuditLogger_Expecter{mock: &_m.Mock}
}

// Log provides a mock function for the type AuditLogger
func (_mock *AuditLogger) Log(ctx context.Context, meta *domain.AuditMeta, action enum.ActionName, actor *domain.AuditUser, target *domain.AuditUser) error {
	ret := _mock.Called(ctx, meta, action, actor, target)

	if len(ret) == 0 {
		panic("no return value specified for Log")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *domain.AuditMeta, enum.ActionName, *domain.AuditUser, *domain.AuditUser) error); ok {
		r0 = returnFunc(ctx, meta, action, actor, target)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// AuditLogger_Log_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Log'
type AuditLogger_Log_Call struct {
	*mock.Call
}

// Log is a helper method to define mock.On call
//   - ctx context.Context
//   - meta *domain.AuditMeta
//   - action enum.ActionName
//   - actor *domain.AuditUser
//   - target *domain.AuditUser
func (_e *AuditLogger_Expecter) Log(ctx interface{}, meta interface{}, action interface{}, actor interface{}, target interface{}) *AuditLogger_Log_Call {
	return &AuditLogger_Log_Call{Call: _e.mock.On("Log", ctx, meta, action, actor, target)}
}

func (_c *AuditLogger_Log_Call) Run(run func(ctx context.Context, meta *domain.AuditMeta, action enum.ActionName, actor *domain.AuditUser, target *domain.AuditUser)) *AuditLogger_Log_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *domain.AuditMeta
		if args[1] != nil {
			arg1 = args[1].(*domain.AuditMeta)
		}
		var arg2 enum.ActionName
		if args[2] != nil {
			arg2 = args[2].(enum.ActionName)
		}
		var arg3 *domain.AuditUser
		if args[3] != nil {
			arg3 = args[3].(*domain.AuditUser)
		}
		var arg4 *domain.AuditUser
		if args[4] != nil {
			arg4 = args[4].(*domain.AuditUser)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
			arg4,
		)
	})
	return _c
}

func (_c *AuditLogger_Log_Call) Return(err error) *AuditLogger_Log_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *AuditLogger_Log_Call) RunAndReturn(run func(ctx context.Context, meta *domain.AuditMeta, action enum.ActionName, actor *domain.AuditUser, target *domain.AuditUser) error) *AuditLogger_Log_Call {
	_c.Call.Return(run)
	return _c
}

// LogWithMetadata provides a mock function for the type AuditLogger
func (_mock *AuditLogger) LogWithMetadata(ctx context.Context, meta *domain.AuditMeta, action enum.ActionName, actor *domain.AuditUser, target *domain.AuditUser, data map[string]any) error {
	ret := _mock.Called(ctx, meta, action, actor, target, data)

	if len(ret) == 0 {
		panic("no return value specified for LogWithMetadata")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *domain.AuditMeta, enum.ActionName, *domain.AuditUser, *domain.AuditUser, map[string]any) error); ok {
		r0 = returnFunc(ctx, meta, action, actor, target, data)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// AuditLogger_LogWithMetadata_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'LogWithMetadata'
type AuditLogger_LogWithMetadata_Call struct {
	*mock.Call
}

// LogWithMetadata is a helper method to define mock.On call
//   - ctx context.Context
//   - meta *domain.AuditMeta
//   - action enum.ActionName
//   - actor *domain.AuditUser
//   - target *domain.AuditUser
//   - data map[string]any
func (_e *AuditLogger_Expecter) LogWithMetadata(ctx interface{}, meta interface{}, action interface{}, actor interface{}, target interface{}, data interface{}) *AuditLogger_LogWithMetadata_Call {
	return &AuditLogger_LogWithMetadata_Call{Call: _e.mock.On("LogWithMetadata", ctx, meta, action, actor, target, data)}
}

func (_c *AuditLogger_LogWithMetadata_Call) Run(run func(ctx context.Context, meta *domain.AuditMeta, action enum.ActionName, actor *domain.AuditUser, target *domain.AuditUser, data map[string]any)) *AuditLogger_LogWithMetadata_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *domain.AuditMeta
		if args[1] != nil {
			arg1 = args[1].(*domain.AuditMeta)
		}
		var arg2 enum.ActionName
		if args[2] != nil {
			arg2 = args[2].(enum.ActionName)
		}
		var arg3 *domain.AuditUser
		if args[3] != nil {
			arg3 = args[3].(*domain.AuditUser)
		}
		var arg4 *domain.AuditUser
		if args[4] != nil {
			arg4 = args[4].(*domain.AuditUser)
		}
		var arg5 map[string]any
		if args[5] != nil {
			arg5 = args[5].(map[string]any)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
			arg4,
			arg5,
		)
	})
	return _c
}

func (_c *AuditLogger_LogWithMetadata_Call) Return(err error) *AuditLogger_LogWithMetadata_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *AuditLogger_LogWithMetadata_Call) RunAndReturn(run func(ctx context.Context, meta *domain.AuditMeta, action enum.ActionName, actor *domain.AuditUser, target *domain.AuditUser, data map[string]any) error) *AuditLogger_LogWithMetadata_Call {
	_c.Call.Return(run)
	return _c
}
