// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package servicesmocks

import (
	"context"
	"portal-system/internal/domain"
	"portal-system/internal/domain/enum"
	"time"

	"github.com/google/uuid"
	mock "github.com/stretchr/testify/mock"
)

// NewAuthService creates a new instance of AuthService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewAuthService(t interface {
	mock.TestingT
	Cleanup(func())
}) *AuthService {
	mock := &AuthService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// AuthService is an autogenerated mock type for the AuthService type
type AuthService struct {
	mock.Mock
}

type AuthService_Expecter struct {
	mock *mock.Mock
}

func (_m *AuthService) EXPECT() *AuthService_Expecter {
	return &AuthService_Expecter{mock: &_m.Mock}
}

// ForgotPassword provides a mock function for the type AuthService
func (_mock *AuthService) ForgotPassword(ctx context.Context, meta *domain.AuditMeta, email string) error {
	ret := _mock.Called(ctx, meta, email)

	if len(ret) == 0 {
		panic("no return value specified for ForgotPassword")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *domain.AuditMeta, string) error); ok {
		r0 = returnFunc(ctx, meta, email)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// AuthService_ForgotPassword_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ForgotPassword'
type AuthService_ForgotPassword_Call struct {
	*mock.Call
}

// ForgotPassword is a helper method to define mock.On call
//   - ctx context.Context
//   - meta *domain.AuditMeta
//   - email string
func (_e *AuthService_Expecter) ForgotPassword(ctx interface{}, meta interface{}, email interface{}) *AuthService_ForgotPassword_Call {
	return &AuthService_ForgotPassword_Call{Call: _e.mock.On("ForgotPassword", ctx, meta, email)}
}

func (_c *AuthService_ForgotPassword_Call) Run(run func(ctx context.Context, meta *domain.AuditMeta, email string)) *AuthService_ForgotPassword_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *domain.AuditMeta
		if args[1] != nil {
			arg1 = args[1].(*domain.AuditMeta)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *AuthService_ForgotPassword_Call) Return(err error) *AuthService_ForgotPassword_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *AuthService_ForgotPassword_Call) RunAndReturn(run func(ctx context.Context, meta *domain.AuditMeta, email string) error) *AuthService_ForgotPassword_Call {
	_c.Call.Return(run)
	return _c
}

// LogIn provides a mock function for the type AuthService
func (_mock *AuthService) LogIn(ctx context.Context, meta *domain.AuditMeta, identifier string, password string) (*domain.LoginResult, error) {
	ret := _mock.Called(ctx, meta, identifier, password)

	if len(ret) == 0 {
		panic("no return value specified for LogIn")
	}

	var r0 *domain.LoginResult
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *domain.AuditMeta, string, string) (*domain.LoginResult, error)); ok {
		return returnFunc(ctx, meta, identifier, password)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *domain.AuditMeta, string, string) *domain.LoginResult); ok {
		r0 = returnFunc(ctx, meta, identifier, password)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.LoginResult)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *domain.AuditMeta, string, string) error); ok {
		r1 = returnFunc(ctx, meta, identifier, password)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// AuthService_LogIn_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'LogIn'
type AuthService_LogIn_Call struct {
	*mock.Call
}

// LogIn is a helper method to define mock.On call
//   - ctx context.Context
//   - meta *domain.AuditMeta
//   - identifier string
//   - password string
func (_e *AuthService_Expecter) LogIn(ctx interface{}, meta interface{}, identifier interface{}, password interface{}) *AuthService_LogIn_Call {
	return &AuthService_LogIn_Call{Call: _e.mock.On("LogIn", ctx, meta, identifier, password)}
}

func (_c *AuthService_LogIn_Call) Run(run func(ctx context.Context, meta *domain.AuditMeta, identifier string, password string)) *AuthService_LogIn_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *domain.AuditMeta
		if args[1] != nil {
			arg1 = args[1].(*domain.AuditMeta)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 string
		if args[3] != nil {
			arg3 = args[3].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *AuthService_LogIn_Call) Return(loginResult *domain.LoginResult, err error) *AuthService_LogIn_Call {
	_c.Call.Return(loginResult, err)
	return _c
}

func (_c *AuthService_LogIn_Call) RunAndReturn(run func(ctx context.Context, meta *domain.AuditMeta, identifier string, password string) (*domain.LoginResult, error)) *AuthService_LogIn_Call {
	_c.Call.Return(run)
	return _c
}

// Logout provides a mock function for the type AuthService
func (_mock *AuthService) Logout(ctx context.Context, meta *domain.AuditMeta, actor *domain.AuditUser, sessionID uuid.UUID) error {
	ret := _mock.Called(ctx, meta, actor, sessionID)

	if len(ret) == 0 {
		panic("no return value specified for Logout")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *domain.AuditMeta, *domain.AuditUser, uuid.UUID) error); ok {
		r0 = returnFunc(ctx, meta, actor, sessionID)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// AuthService_Logout_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Logout'
type AuthService_Logout_Call struct {
	*mock.Call
}

// Logout is a helper method to define mock.On call
//   - ctx context.Context
//   - meta *domain.AuditMeta
//   - actor *domain.AuditUser
//   - sessionID uuid.UUID
func (_e *AuthService_Expecter) Logout(ctx interface{}, meta interface{}, actor interface{}, sessionID interface{}) *AuthService_Logout_Call {
	return &AuthService_Logout_Call{Call: _e.mock.On("Logout", ctx, meta, actor, sessionID)}
}

func (_c *AuthService_Logout_Call) Run(run func(ctx context.Context, meta *domain.AuditMeta, actor *domain.AuditUser, sessionID uuid.UUID)) *AuthService_Logout_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *domain.AuditMeta
		if args[1] != nil {
			arg1 = args[1].(*domain.AuditMeta)
		}
		var arg2 *domain.AuditUser
		if args[2] != nil {
			arg2 = args[2].(*domain.AuditUser)
		}
		var arg3 uuid.UUID
		if args[3] != nil {
			arg3 = args[3].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *AuthService_Logout_Call) Return(err error) *AuthService_Logout_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *AuthService_Logout_Call) RunAndReturn(run func(ctx context.Context, meta *domain.AuditMeta, actor *domain.AuditUser, sessionID uuid.UUID) error) *AuthService_Logout_Call {
	_c.Call.Return(run)
	return _c
}

// LogoutAll provides a mock function for the type AuthService
func (_mock *AuthService) LogoutAll(ctx context.Context, meta *domain.AuditMeta, actor *domain.AuditUser) error {
	ret := _mock.Called(ctx, meta, actor)

	if len(ret) == 0 {
		panic("no return value specified for LogoutAll")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *domain.AuditMeta, *domain.AuditUser) error); ok {
		r0 = returnFunc(ctx, meta, actor)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// AuthService_LogoutAll_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'LogoutAll'
type AuthService_LogoutAll_Call struct {
	*mock.Call
}

// LogoutAll is a helper method to define mock.On call
//   - ctx context.Context
//   - meta *domain.AuditMeta
//   - actor *domain.AuditUser
func (_e *AuthService_Expecter) LogoutAll(ctx interface{}, meta interface{}, actor interface{}) *AuthService_LogoutAll_Call {
	return &AuthService_LogoutAll_Call{Call: _e.mock.On("LogoutAll", ctx, meta, actor)}
}

func (_c *AuthService_LogoutAll_Call) Run(run func(ctx context.Context, meta *domain.AuditMeta, actor *domain.AuditUser)) *AuthService_LogoutAll_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *domain.AuditMeta
		if args[1] != nil {
			arg1 = args[1].(*domain.AuditMeta)
		}
		var arg2 *domain.AuditUser
		if args[2] != nil {
			arg2 = args[2].(*domain.AuditUser)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *AuthService_LogoutAll_Call) Return(err error) *AuthService_LogoutAll_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *AuthService_LogoutAll_Call) RunAndReturn(run func(ctx context.Context, meta *domain.AuditMeta, actor *domain.AuditUser) error) *AuthService_LogoutAll_Call {
	_c.Call.Return(run)
	return _c
}

// Refresh provides a mock function for the type AuthService
func (_mock *AuthService) Refresh(ctx context.Context, meta *domain.AuditMeta, refreshToken string) (*domain.RefreshResult, error) {
	ret := _mock.Called(ctx, meta, refreshToken)

	if len(ret) == 0 {
		panic("no return value specified for Refresh")
	}

	var r0 *domain.RefreshResult
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *domain.AuditMeta, string) (*domain.RefreshResult, error)); ok {
		return returnFunc(ctx, meta, refreshToken)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *domain.AuditMeta, string) *domain.RefreshResult); ok {
		r0 = returnFunc(ctx, meta, refreshToken)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.RefreshResult)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *domain.AuditMeta, string) error); ok {
		r1 = returnFunc(ctx, meta, refreshToken)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// AuthService_Refresh_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Refresh'
type AuthService_Refresh_Call struct {
	*mock.Call
}

// Refresh is a helper method to define mock.On call
//   - ctx context.Context
//   - meta *domain.AuditMeta
//   - refreshToken string
func (_e *AuthService_Expecter) Refresh(ctx interface{}, meta interface{}, refreshToken interface{}) *AuthService_Refresh_Call {
	return &AuthService_Refresh_Call{Call: _e.mock.On("Refresh", ctx, meta, refreshToken)}
}

func (_c *AuthService_Refresh_Call) Run(run func(ctx context.Context, meta *domain.AuditMeta, refreshToken string)) *AuthService_Refresh_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *domain.AuditMeta
		if args[1] != nil {
			arg1 = args[1].(*domain.AuditMeta)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *AuthService_Refresh_Call) Return(refreshResult *domain.RefreshResult, err error) *AuthService_Refresh_Call {
	_c.Call.Return(refreshResult, err)
	return _c
}

func (_c *AuthService_Refresh_Call) RunAndReturn(run func(ctx context.Context, meta *domain.AuditMeta, refreshToken string) (*domain.RefreshResult, error)) *AuthService_Refresh_Call {
	_c.Call.Return(run)
	return _c
}

// Register provides a mock function for the type AuthService
func (_mock *AuthService) Register(ctx context.Context, meta *domain.AuditMeta, email string, username string, password string, firstName string, lastName string, dob time.Time) error {
	ret := _mock.Called(ctx, meta, email, username, password, firstName, lastName, dob)

	if len(ret) == 0 {
		panic("no return value specified for Register")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *domain.AuditMeta, string, string, string, string, string, time.Time) error); ok {
		r0 = returnFunc(ctx, meta, email, username, password, firstName, lastName, dob)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// AuthService_Register_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Register'
type AuthService_Register_Call struct {
	*mock.Call
}

// Register is a helper method to define mock.On call
//   - ctx context.Context
//   - meta *domain.AuditMeta
//   - email string
//   - username string
//   - password string
//   - firstName string
//   - lastName string
//   - dob time.Time
func (_e *AuthService_Expecter) Register(ctx interface{}, meta interface{}, email interface{}, username interface{}, password interface{}, firstName interface{}, lastName interface{}, dob interface{}) *AuthService_Register_Call {
	return &AuthService_Register_Call{Call: _e.mock.On("Register", ctx, meta, email, username, password, firstName, lastName, dob)}
}

func (_c *AuthService_Register_Call) Run(run func(ctx context.Context, meta *domain.AuditMeta, email string, username string, password string, firstName string, lastName string, dob time.Time)) *AuthService_Register_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *domain.AuditMeta
		if args[1] != nil {
			arg1 = args[1].(*domain.AuditMeta)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 string
		if args[3] != nil {
			arg3 = args[3].(string)
		}
		var arg4 string
		if args[4] != nil {
			arg4 = args[4].(string)
		}
		var arg5 string
		if args[5] != nil {
			arg5 = args[5].(string)
		}
		var arg6 string
		if args[6] != nil {
			arg6 = args[6].(string)
		}
		var arg7 time.Time
		if args[7] != nil {
			arg7 = args[7].(time.Time)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
			arg4,
			arg5,
			arg6,
			arg7,
		)
	})
	return _c
}

func (_c *AuthService_Register_Call) Return(err error) *AuthService_Register_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *AuthService_Register_Call) RunAndReturn(run func(ctx context.Context, meta *domain.AuditMeta, email string, username string, password string, firstName string, lastName string, dob time.Time) error) *AuthService_Register_Call {
	_c.Call.Return(run)
	return _c
}

// ResendVerification provides a mock function for the type AuthService
func (_mock *AuthService) ResendVerification(ctx context.Context, meta *domain.AuditMeta, email string, tokenType enum.TokenType) error {
	ret := _mock.Called(ctx, meta, email, tokenType)

	if len(ret) == 0 {
		panic("no return value specified for ResendVerification")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *domain.AuditMeta, string, enum.TokenType) error); ok {
		r0 = returnFunc(ctx, meta, email, tokenType)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// AuthService_ResendVerification_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ResendVerification'
type AuthService_ResendVerification_Call struct {
	*mock.Call
}

// ResendVerification is a helper method to define mock.On call
//   - ctx context.Context
//   - meta *domain.AuditMeta
//   - email string
//   - tokenType enum.TokenType
func (_e *AuthService_Expecter) ResendVerification(ctx interface{}, meta interface{}, email interface{}, tokenType interface{}) *AuthService_ResendVerification_Call {
	return &AuthService_ResendVerification_Call{Call: _e.mock.On("ResendVerification", ctx, meta, email, tokenType)}
}

func (_c *AuthService_ResendVerification_Call) Run(run func(ctx context.Context, meta *domain.AuditMeta, email string, tokenType enum.TokenType)) *AuthService_ResendVerification_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *domain.AuditMeta
		if args[1] != nil {
			arg1 = args[1].(*domain.AuditMeta)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 enum.TokenType
		if args[3] != nil {
			arg3 = args[3].(enum.TokenType)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *AuthService_ResendVerification_Call) Return(err error) *AuthService_ResendVerification_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *AuthService_ResendVerification_Call) RunAndReturn(run func(ctx context.Context, meta *domain.AuditMeta, email string, tokenType enum.TokenType) error) *AuthService_ResendVerification_Call {
	_c.Call.Return(run)
	return _c
}

// ResetPassword provides a mock function for the type AuthService
func (_mock *AuthService) ResetPassword(ctx context.Context, meta *domain.AuditMeta, in *domain.SetPasswordInput, tokenType enum.TokenType) error {
	ret := _mock.Called(ctx, meta, in, tokenType)

	if len(ret) == 0 {
		panic("no return value specified for ResetPassword")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *domain.AuditMeta, *domain.SetPasswordInput, enum.TokenType) error); ok {
		r0 = returnFunc(ctx, meta, in, tokenType)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// AuthService_ResetPassword_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ResetPassword'
type AuthService_ResetPassword_Call struct {
	*mock.Call
}

// ResetPassword is a helper method to define mock.On call
//   - ctx context.Context
//   - meta *domain.AuditMeta
//   - in *domain.SetPasswordInput
//   - tokenType enum.TokenType
func (_e *AuthService_Expecter) ResetPassword(ctx interface{}, meta interface{}, in interface{}, tokenType interface{}) *AuthService_ResetPassword_Call {
	return &AuthService_ResetPassword_Call{Call: _e.mock.On("ResetPassword", ctx, meta, in, tokenType)}
}

func (_c *AuthService_ResetPassword_Call) Run(run func(ctx context.Context, meta *domain.AuditMeta, in *domain.SetPasswordInput, tokenType enum.TokenType)) *AuthService_ResetPassword_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *domain.AuditMeta
		if args[1] != nil {
			arg1 = args[1].(*domain.AuditMeta)
		}
		var arg2 *domain.SetPasswordInput
		if args[2] != nil {
			arg2 = args[2].(*domain.SetPasswordInput)
		}
		var arg3 enum.TokenType
		if args[3] != nil {
			arg3 = args[3].(enum.TokenType)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *AuthService_ResetPassword_Call) Return(err error) *AuthService_ResetPassword_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *AuthService_ResetPassword_Call) RunAndReturn(run func(ctx context.Context, meta *domain.AuditMeta, in *domain.SetPasswordInput, tokenType enum.TokenType) error) *AuthService_ResetPassword_Call {
	_c.Call.Return(run)
	return _c
}

// SetPassword provides a mock function for the type AuthService
func (_mock *AuthService) SetPassword(ctx context.Context, meta *domain.AuditMeta, in *domain.SetPasswordInput, tokenType enum.TokenType) error {
	ret := _mock.Called(ctx, meta, in, tokenType)

	if len(ret) == 0 {
		panic("no return value specified for SetPassword")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *domain.AuditMeta, *domain.SetPasswordInput, enum.TokenType) error); ok {
		r0 = returnFunc(ctx, meta, in, tokenType)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// AuthService_SetPassword_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetPassword'
type AuthService_SetPassword_Call struct {
	*mock.Call
}

// SetPassword is a helper method to define mock.On call
//   - ctx context.Context
//   - meta *domain.AuditMeta
//   - in *domain.SetPasswordInput
//   - tokenType enum.TokenType
func (_e *AuthService_Expecter) SetPassword(ctx interface{}, meta interface{}, in interface{}, tokenType interface{}) *AuthService_SetPassword_Call {
	return &AuthService_SetPassword_Call{Call: _e.mock.On("SetPassword", ctx, meta, in, tokenType)}
}

func (_c *AuthService_SetPassword_Call) Run(run func(ctx context.Context, meta *domain.AuditMeta, in *domain.SetPasswordInput, tokenType enum.TokenType)) *AuthService_SetPassword_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *domain.AuditMeta
		if args[1] != nil {
			arg1 = args[1].(*domain.AuditMeta)
		}
		var arg2 *domain.SetPasswordInput
		if args[2] != nil {
			arg2 = args[2].(*domain.SetPasswordInput)
		}
		var arg3 enum.TokenType
		if args[3] != nil {
			arg3 = args[3].(enum.TokenType)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *AuthService_SetPassword_Call) Return(err error) *AuthService_SetPassword_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *AuthService_SetPassword_Call) RunAndReturn(run func(ctx context.Context, meta *domain.AuditMeta, in *domain.SetPasswordInput, tokenType enum.TokenType) error) *AuthService_SetPassword_Call {
	_c.Call.Return(run)
	return _c
}

// VerifyEmail provides a mock function for the type AuthService
func (_mock *AuthService) VerifyEmail(ctx context.Context, meta *domain.AuditMeta, rawToken string, tokenType enum.TokenType) error {
	ret := _mock.Called(ctx, meta, rawToken, tokenType)

	if len(ret) == 0 {
		panic("no return value specified for VerifyEmail")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *domain.AuditMeta, string, enum.TokenType) error); ok {
		r0 = returnFunc(ctx, meta, rawToken, tokenType)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// AuthService_VerifyEmail_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'VerifyEmail'
type AuthService_VerifyEmail_Call struct {
	*mock.Call
}

// VerifyEmail is a helper method to define mock.On call
//   - ctx context.Context
//   - meta *domain.AuditMeta
//   - rawToken string
//   - tokenType enum.TokenType
func (_e *AuthService_Expecter) VerifyEmail(ctx interface{}, meta interface{}, rawToken interface{}, tokenType interface{}) *AuthService_VerifyEmail_Call {
	return &AuthService_VerifyEmail_Call{Call: _e.mock.On("VerifyEmail", ctx, meta, rawToken, tokenType)}
}

func (_c *AuthService_VerifyEmail_Call) Run(run func(ctx context.Context, meta *domain.AuditMeta, rawToken string, tokenType enum.TokenType)) *AuthService_VerifyEmail_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *domain.AuditMeta
		if args[1] != nil {
			arg1 = args[1].(*domain.AuditMeta)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 enum.TokenType
		if args[3] != nil {
			arg3 = args[3].(enum.TokenType)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *AuthService_VerifyEmail_Call) Return(err error) *AuthService_VerifyEmail_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *AuthService_VerifyEmail_Call) RunAndReturn(run func(ctx context.Context, meta *domain.AuditMeta, rawToken string, tokenType enum.TokenType) error) *AuthService_VerifyEmail_Call {
	_c.Call.Return(run)
	return _c
}
