// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package servicesmocks

import (
	"context"

	mock "github.com/stretchr/testify/mock"
)

// NewEmailSender creates a new instance of EmailSender. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewEmailSender(t interface {
	mock.TestingT
	Cleanup(func())
}) *EmailSender {
	mock := &EmailSender{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// EmailSender is an autogenerated mock type for the EmailSender type
type EmailSender struct {
	mock.Mock
}

type EmailSender_Expecter struct {
	mock *mock.Mock
}

func (_m *EmailSender) EXPECT() *EmailSender_Expecter {
	return &EmailSender_Expecter{mock: &_m.Mock}
}

// SendResetPasswordEmail provides a mock function for the type EmailSender
func (_mock *EmailSender) SendResetPasswordEmail(ctx context.Context, to string, name string, resetURL string) error {
	ret := _mock.Called(ctx, to, name, resetURL)

	if len(ret) == 0 {
		panic("no return value specified for SendResetPasswordEmail")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, string) error); ok {
		r0 = returnFunc(ctx, to, name, resetURL)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// EmailSender_SendResetPasswordEmail_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SendResetPasswordEmail'
type EmailSender_SendResetPasswordEmail_Call struct {
	*mock.Call
}

// SendResetPasswordEmail is a helper method to define mock.On call
//   - ctx context.Context
//   - to string
//   - name string
//   - resetURL string
func (_e *EmailSender_Expecter) SendResetPasswordEmail(ctx interface{}, to interface{}, name interface{}, resetURL interface{}) *EmailSender_SendResetPasswordEmail_Call {
	return &EmailSender_SendResetPasswordEmail_Call{Call: _e.mock.On("SendResetPasswordEmail", ctx, to, name, resetURL)}
}

func (_c *EmailSender_SendResetPasswordEmail_Call) Run(run func(ctx context.Context, to string, name string, resetURL string)) *EmailSender_SendResetPasswordEmail_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 string
		if args[3] != nil {
			arg3 = args[3].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *EmailSender_SendResetPasswordEmail_Call) Return(err error) *EmailSender_SendResetPasswordEmail_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *EmailSender_SendResetPasswordEmail_Call) RunAndReturn(run func(ctx context.Context, to string, name string, resetURL string) error) *EmailSender_SendResetPasswordEmail_Call {
	_c.Call.Return(run)
	return _c
}

// SendSetPasswordEmail provides a mock function for the type EmailSender
func (_mock *EmailSender) SendSetPasswordEmail(ctx context.Context, to string, name string, setPasswordURL string) error {
	ret := _mock.Called(ctx, to, name, setPasswordURL)

	if len(ret) == 0 {
		panic("no return value specified for SendSetPasswordEmail")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, string) error); ok {
		r0 = returnFunc(ctx, to, name, setPasswordURL)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// EmailSender_SendSetPasswordEmail_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SendSetPasswordEmail'
type EmailSender_SendSetPasswordEmail_Call struct {
	*mock.Call
}

// SendSetPasswordEmail is a helper method to define mock.On call
//   - ctx context.Context
//   - to string
//   - name string
//   - setPasswordURL string
func (_e *EmailSender_Expecter) SendSetPasswordEmail(ctx interface{}, to interface{}, name interface{}, setPasswordURL interface{}) *EmailSender_SendSetPasswordEmail_Call {
	return &EmailSender_SendSetPasswordEmail_Call{Call: _e.mock.On("SendSetPasswordEmail", ctx, to, name, setPasswordURL)}
}

func (_c *EmailSender_SendSetPasswordEmail_Call) Run(run func(ctx context.Context, to string, name string, setPasswordURL string)) *EmailSender_SendSetPasswordEmail_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 string
		if args[3] != nil {
			arg3 = args[3].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *EmailSender_SendSetPasswordEmail_Call) Return(err error) *EmailSender_SendSetPasswordEmail_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *EmailSender_SendSetPasswordEmail_Call) RunAndReturn(run func(ctx context.Context, to string, name string, setPasswordURL string) error) *EmailSender_SendSetPasswordEmail_Call {
	_c.Call.Return(run)
	return _c
}

// SendVerificationEmail provides a mock function for the type EmailSender
func (_mock *EmailSender) SendVerificationEmail(ctx context.Context, to string, name string, verifyURL string) error {
	ret := _mock.Called(ctx, to, name, verifyURL)

	if len(ret) == 0 {
		panic("no return value specified for SendVerificationEmail")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, string) error); ok {
		r0 = returnFunc(ctx, to, name, verifyURL)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// EmailSender_SendVerificationEmail_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SendVerificationEmail'
type EmailSender_SendVerificationEmail_Call struct {
	*mock.Call
}

// SendVerificationEmail is a helper method to define mock.On call
//   - ctx context.Context
//   - to string
//   - name string
//   - verifyURL string
func (_e *EmailSender_Expecter) SendVerificationEmail(ctx interface{}, to interface{}, name interface{}, verifyURL interface{}) *EmailSender_SendVerificationEmail_Call {
	return &EmailSender_SendVerificationEmail_Call{Call: _e.mock.On("SendVerificationEmail", ctx, to, name, verifyURL)}
}

func (_c *EmailSender_SendVerificationEmail_Call) Run(run func(ctx context.Context, to string, name string, verifyURL string)) *EmailSender_SendVerificationEmail_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 string
		if args[3] != nil {
			arg3 = args[3].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *EmailSender_SendVerificationEmail_Call) Return(err error) *EmailSender_SendVerificationEmail_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *EmailSender_SendVerificationEmail_Call) RunAndReturn(run func(ctx context.Context, to string, name string, verifyURL string) error) *EmailSender_SendVerificationEmail_Call {
	_c.Call.Return(run)
	return _c
}
