// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package servicesmocks

import (
	"portal-system/internal/services"

	mock "github.com/stretchr/testify/mock"
)

// NewTokenIssuer creates a new instance of TokenIssuer. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewTokenIssuer(t interface {
	mock.TestingT
	Cleanup(func())
}) *TokenIssuer {
	mock := &TokenIssuer{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// TokenIssuer is an autogenerated mock type for the TokenIssuer type
type TokenIssuer struct {
	mock.Mock
}

type TokenIssuer_Expecter struct {
	mock *mock.Mock
}

func (_m *TokenIssuer) EXPECT() *TokenIssuer_Expecter {
	return &TokenIssuer_Expecter{mock: &_m.Mock}
}

// ExpiresInSeconds provides a mock function for the type TokenIssuer
func (_mock *TokenIssuer) ExpiresInSeconds() int {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for ExpiresInSeconds")
	}

	var r0 int
	if returnFunc, ok := ret.Get(0).(func() int); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(int)
	}
	return r0
}

// TokenIssuer_ExpiresInSeconds_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ExpiresInSeconds'
type TokenIssuer_ExpiresInSeconds_Call struct {
	*mock.Call
}

// ExpiresInSeconds is a helper method to define mock.On call
func (_e *TokenIssuer_Expecter) ExpiresInSeconds() *TokenIssuer_ExpiresInSeconds_Call {
	return &TokenIssuer_ExpiresInSeconds_Call{Call: _e.mock.On("ExpiresInSeconds")}
}

func (_c *TokenIssuer_ExpiresInSeconds_Call) Run(run func()) *TokenIssuer_ExpiresInSeconds_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *TokenIssuer_ExpiresInSeconds_Call) Return(n int) *TokenIssuer_ExpiresInSeconds_Call {
	_c.Call.Return(n)
	return _c
}

func (_c *TokenIssuer_ExpiresInSeconds_Call) RunAndReturn(run func() int) *TokenIssuer_ExpiresInSeconds_Call {
	_c.Call.Return(run)
	return _c
}

// GenerateAccessToken provides a mock function for the type TokenIssuer
func (_mock *TokenIssuer) GenerateAccessToken(input services.GenerateAccessTokenInput) (string, error) {
	ret := _mock.Called(input)

	if len(ret) == 0 {
		panic("no return value specified for GenerateAccessToken")
	}

	var r0 string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(services.GenerateAccessTokenInput) (string, error)); ok {
		return returnFunc(input)
	}
	if returnFunc, ok := ret.Get(0).(func(services.GenerateAccessTokenInput) string); ok {
		r0 = returnFunc(input)
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func(services.GenerateAccessTokenInput) error); ok {
		r1 = returnFunc(input)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// TokenIssuer_GenerateAccessToken_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GenerateAccessToken'
type TokenIssuer_GenerateAccessToken_Call struct {
	*mock.Call
}

// GenerateAccessToken is a helper method to define mock.On call
//   - input services.GenerateAccessTokenInput
func (_e *TokenIssuer_Expecter) GenerateAccessToken(input interface{}) *TokenIssuer_GenerateAccessToken_Call {
	return &TokenIssuer_GenerateAccessToken_Call{Call: _e.mock.On("GenerateAccessToken", input)}
}

func (_c *TokenIssuer_GenerateAccessToken_Call) Run(run func(input services.GenerateAccessTokenInput)) *TokenIssuer_GenerateAccessToken_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 services.GenerateAccessTokenInput
		if args[0] != nil {
			arg0 = args[0].(services.GenerateAccessTokenInput)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *TokenIssuer_GenerateAccessToken_Call) Return(s string, err error) *TokenIssuer_GenerateAccessToken_Call {
	_c.Call.Return(s, err)
	return _c
}

func (_c *TokenIssuer_GenerateAccessToken_Call) RunAndReturn(run func(input services.GenerateAccessTokenInput) (string, error)) *TokenIssuer_GenerateAccessToken_Call {
	_c.Call.Return(run)
	return _c
}

// GenerateHashToken provides a mock function for the type TokenIssuer
func (_mock *TokenIssuer) GenerateHashToken() (string, string, error) {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for GenerateHashToken")
	}

	var r0 string
	var r1 string
	var r2 error
	if returnFunc, ok := ret.Get(0).(func() (string, string, error)); ok {
		return returnFunc()
	}
	if returnFunc, ok := ret.Get(0).(func() string); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func() string); ok {
		r1 = returnFunc()
	} else {
		r1 = ret.Get(1).(string)
	}
	if returnFunc, ok := ret.Get(2).(func() error); ok {
		r2 = returnFunc()
	} else {
		r2 = ret.Error(2)
	}
	return r0, r1, r2
}

// TokenIssuer_GenerateHashToken_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GenerateHashToken'
type TokenIssuer_GenerateHashToken_Call struct {
	*mock.Call
}

// GenerateHashToken is a helper method to define mock.On call
func (_e *TokenIssuer_Expecter) GenerateHashToken() *TokenIssuer_GenerateHashToken_Call {
	return &TokenIssuer_GenerateHashToken_Call{Call: _e.mock.On("GenerateHashToken")}
}

func (_c *TokenIssuer_GenerateHashToken_Call) Run(run func()) *TokenIssuer_GenerateHashToken_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *TokenIssuer_GenerateHashToken_Call) Return(s string, s1 string, err error) *TokenIssuer_GenerateHashToken_Call {
	_c.Call.Return(s, s1, err)
	return _c
}

func (_c *TokenIssuer_GenerateHashToken_Call) RunAndReturn(run func() (string, string, error)) *TokenIssuer_GenerateHashToken_Call {
	_c.Call.Return(run)
	return _c
}

// GenerateRefreshToken provides a mock function for the type TokenIssuer
func (_mock *TokenIssuer) GenerateRefreshToken() (string, error) {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for GenerateRefreshToken")
	}

	var r0 string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func() (string, error)); ok {
		return returnFunc()
	}
	if returnFunc, ok := ret.Get(0).(func() string); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func() error); ok {
		r1 = returnFunc()
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// TokenIssuer_GenerateRefreshToken_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GenerateRefreshToken'
type TokenIssuer_GenerateRefreshToken_Call struct {
	*mock.Call
}

// GenerateRefreshToken is a helper method to define mock.On call
func (_e *TokenIssuer_Expecter) GenerateRefreshToken() *TokenIssuer_GenerateRefreshToken_Call {
	return &TokenIssuer_GenerateRefreshToken_Call{Call: _e.mock.On("GenerateRefreshToken")}
}

func (_c *TokenIssuer_GenerateRefreshToken_Call) Run(run func()) *TokenIssuer_GenerateRefreshToken_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *TokenIssuer_GenerateRefreshToken_Call) Return(s string, err error) *TokenIssuer_GenerateRefreshToken_Call {
	_c.Call.Return(s, err)
	return _c
}

func (_c *TokenIssuer_GenerateRefreshToken_Call) RunAndReturn(run func() (string, error)) *TokenIssuer_GenerateRefreshToken_Call {
	_c.Call.Return(run)
	return _c
}

// HashToken provides a mock function for the type TokenIssuer
func (_mock *TokenIssuer) HashToken(raw string) string {
	ret := _mock.Called(raw)

	if len(ret) == 0 {
		panic("no return value specified for HashToken")
	}

	var r0 string
	if returnFunc, ok := ret.Get(0).(func(string) string); ok {
		r0 = returnFunc(raw)
	} else {
		r0 = ret.Get(0).(string)
	}
	return r0
}

// TokenIssuer_HashToken_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'HashToken'
type TokenIssuer_HashToken_Call struct {
	*mock.Call
}

// HashToken is a helper method to define mock.On call
//   - raw string
func (_e *TokenIssuer_Expecter) HashToken(raw interface{}) *TokenIssuer_HashToken_Call {
	return &TokenIssuer_HashToken_Call{Call: _e.mock.On("HashToken", raw)}
}

func (_c *TokenIssuer_HashToken_Call) Run(run func(raw string)) *TokenIssuer_HashToken_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *TokenIssuer_HashToken_Call) Return(s string) *TokenIssuer_HashToken_Call {
	_c.Call.Return(s)
	return _c
}

func (_c *TokenIssuer_HashToken_Call) RunAndReturn(run func(raw string) string) *TokenIssuer_HashToken_Call {
	_c.Call.Return(run)
	return _c
}

// Parse provides a mock function for the type TokenIssuer
func (_mock *TokenIssuer) Parse(tokenString string) (*services.TokenClaims, error) {
	ret := _mock.Called(tokenString)

	if len(ret) == 0 {
		panic("no return value specified for Parse")
	}

	var r0 *services.TokenClaims
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string) (*services.TokenClaims, error)); ok {
		return returnFunc(tokenString)
	}
	if returnFunc, ok := ret.Get(0).(func(string) *services.TokenClaims); ok {
		r0 = returnFunc(tokenString)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*services.TokenClaims)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(string) error); ok {
		r1 = returnFunc(tokenString)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// TokenIssuer_Parse_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Parse'
type TokenIssuer_Parse_Call struct {
	*mock.Call
}

// Parse is a helper method to define mock.On call
//   - tokenString string
func (_e *TokenIssuer_Expecter) Parse(tokenString interface{}) *TokenIssuer_Parse_Call {
	return &TokenIssuer_Parse_Call{Call: _e.mock.On("Parse", tokenString)}
}

func (_c *TokenIssuer_Parse_Call) Run(run func(tokenString string)) *TokenIssuer_Parse_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *TokenIssuer_Parse_Call) Return(claims *services.TokenClaims, err error) *TokenIssuer_Parse_Call {
	_c.Call.Return(claims, err)
	return _c
}

func (_c *TokenIssuer_Parse_Call) RunAndReturn(run func(tokenString string) (*services.TokenClaims, error)) *TokenIssuer_Parse_Call {
	_c.Call.Return(run)
	return _c
}
