// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package servicesmocks

import (
	"context"
	"portal-system/internal/domain"
	"portal-system/internal/models"

	"github.com/google/uuid"
	mock "github.com/stretchr/testify/mock"
)

// NewUserService creates a new instance of UserService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewUserService(t interface {
	mock.TestingT
	Cleanup(func())
}) *UserService {
	mock := &UserService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// UserService is an autogenerated mock type for the UserService type
type UserService struct {
	mock.Mock
}

type UserService_Expecter struct {
	mock *mock.Mock
}

func (_m *UserService) EXPECT() *UserService_Expecter {
	return &UserService_Expecter{mock: &_m.Mock}
}

// ChangePassword provides a mock function for the type UserService
func (_mock *UserService) ChangePassword(ctx context.Context, meta *domain.AuditMeta, actor *domain.AuditUser, current string, newPassword string, confirm string) error {
	ret := _mock.Called(ctx, meta, actor, current, newPassword, confirm)

	if len(ret) == 0 {
		panic("no return value specified for ChangePassword")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *domain.AuditMeta, *domain.AuditUser, string, string, string) error); ok {
		r0 = returnFunc(ctx, meta, actor, current, newPassword, confirm)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// UserService_ChangePassword_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ChangePassword'
type UserService_ChangePassword_Call struct {
	*mock.Call
}

// ChangePassword is a helper method to define mock.On call
//   - ctx context.Context
//   - meta *domain.AuditMeta
//   - actor *domain.AuditUser
//   - current string
//   - newPassword string
//   - confirm string
func (_e *UserService_Expecter) ChangePassword(ctx interface{}, meta interface{}, actor interface{}, current interface{}, newPassword interface{}, confirm interface{}) *UserService_ChangePassword_Call {
	return &UserService_ChangePassword_Call{Call: _e.mock.On("ChangePassword", ctx, meta, actor, current, newPassword, confirm)}
}

func (_c *UserService_ChangePassword_Call) Run(run func(ctx context.Context, meta *domain.AuditMeta, actor *domain.AuditUser, current string, newPassword string, confirm string)) *UserService_ChangePassword_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *domain.AuditMeta
		if args[1] != nil {
			arg1 = args[1].(*domain.AuditMeta)
		}
		var arg2 *domain.AuditUser
		if args[2] != nil {
			arg2 = args[2].(*domain.AuditUser)
		}
		var arg3 string
		if args[3] != nil {
			arg3 = args[3].(string)
		}
		var arg4 string
		if args[4] != nil {
			arg4 = args[4].(string)
		}
		var arg5 string
		if args[5] != nil {
			arg5 = args[5].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
			arg4,
			arg5,
		)
	})
	return _c
}

func (_c *UserService_ChangePassword_Call) Return(err error) *UserService_ChangePassword_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *UserService_ChangePassword_Call) RunAndReturn(run func(ctx context.Context, meta *domain.AuditMeta, actor *domain.AuditUser, current string, newPassword string, confirm string) error) *UserService_ChangePassword_Call {
	_c.Call.Return(run)
	return _c
}

// GetProfile provides a mock function for the type UserService
func (_mock *UserService) GetProfile(ctx context.Context, meta *domain.AuditMeta, actor *domain.AuditUser, id uuid.UUID) (*models.User, error) {
	ret := _mock.Called(ctx, meta, actor, id)

	if len(ret) == 0 {
		panic("no return value specified for GetProfile")
	}

	var r0 *models.User
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *domain.AuditMeta, *domain.AuditUser, uuid.UUID) (*models.User, error)); ok {
		return returnFunc(ctx, meta, actor, id)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *domain.AuditMeta, *domain.AuditUser, uuid.UUID) *models.User); ok {
		r0 = returnFunc(ctx, meta, actor, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.User)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *domain.AuditMeta, *domain.AuditUser, uuid.UUID) error); ok {
		r1 = returnFunc(ctx, meta, actor, id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// UserService_GetProfile_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetProfile'
type UserService_GetProfile_Call struct {
	*mock.Call
}

// GetProfile is a helper method to define mock.On call
//   - ctx context.Context
//   - meta *domain.AuditMeta
//   - actor *domain.AuditUser
//   - id uuid.UUID
func (_e *UserService_Expecter) GetProfile(ctx interface{}, meta interface{}, actor interface{}, id interface{}) *UserService_GetProfile_Call {
	return &UserService_GetProfile_Call{Call: _e.mock.On("GetProfile", ctx, meta, actor, id)}
}

func (_c *UserService_GetProfile_Call) Run(run func(ctx context.Context, meta *domain.AuditMeta, actor *domain.AuditUser, id uuid.UUID)) *UserService_GetProfile_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *domain.AuditMeta
		if args[1] != nil {
			arg1 = args[1].(*domain.AuditMeta)
		}
		var arg2 *domain.AuditUser
		if args[2] != nil {
			arg2 = args[2].(*domain.AuditUser)
		}
		var arg3 uuid.UUID
		if args[3] != nil {
			arg3 = args[3].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *UserService_GetProfile_Call) Return(user *models.User, err error) *UserService_GetProfile_Call {
	_c.Call.Return(user, err)
	return _c
}

func (_c *UserService_GetProfile_Call) RunAndReturn(run func(ctx context.Context, meta *domain.AuditMeta, actor *domain.AuditUser, id uuid.UUID) (*models.User, error)) *UserService_GetProfile_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateProfile provides a mock function for the type UserService
func (_mock *UserService) UpdateProfile(ctx context.Context, meta *domain.AuditMeta, actor *domain.AuditUser, id uuid.UUID, input domain.UpdateUserInput) (*models.User, error) {
	ret := _mock.Called(ctx, meta, actor, id, input)

	if len(ret) == 0 {
		panic("no return value specified for UpdateProfile")
	}

	var r0 *models.User
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *domain.AuditMeta, *domain.AuditUser, uuid.UUID, domain.UpdateUserInput) (*models.User, error)); ok {
		return returnFunc(ctx, meta, actor, id, input)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *domain.AuditMeta, *domain.AuditUser, uuid.UUID, domain.UpdateUserInput) *models.User); ok {
		r0 = returnFunc(ctx, meta, actor, id, input)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.User)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *domain.AuditMeta, *domain.AuditUser, uuid.UUID, domain.UpdateUserInput) error); ok {
		r1 = returnFunc(ctx, meta, actor, id, input)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// UserService_UpdateProfile_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateProfile'
type UserService_UpdateProfile_Call struct {
	*mock.Call
}

// UpdateProfile is a helper method to define mock.On call
//   - ctx context.Context
//   - meta *domain.AuditMeta
//   - actor *domain.AuditUser
//   - id uuid.UUID
//   - input domain.UpdateUserInput
func (_e *UserService_Expecter) UpdateProfile(ctx interface{}, meta interface{}, actor interface{}, id interface{}, input interface{}) *UserService_UpdateProfile_Call {
	return &UserService_UpdateProfile_Call{Call: _e.mock.On("UpdateProfile", ctx, meta, actor, id, input)}
}

func (_c *UserService_UpdateProfile_Call) Run(run func(ctx context.Context, meta *domain.AuditMeta, actor *domain.AuditUser, id uuid.UUID, input domain.UpdateUserInput)) *UserService_UpdateProfile_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *domain.AuditMeta
		if args[1] != nil {
			arg1 = args[1].(*domain.AuditMeta)
		}
		var arg2 *domain.AuditUser
		if args[2] != nil {
			arg2 = args[2].(*domain.AuditUser)
		}
		var arg3 uuid.UUID
		if args[3] != nil {
			arg3 = args[3].(uuid.UUID)
		}
		var arg4 domain.UpdateUserInput
		if args[4] != nil {
			arg4 = args[4].(domain.UpdateUserInput)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
			arg4,
		)
	})
	return _c
}

func (_c *UserService_UpdateProfile_Call) Return(user *models.User, err error) *UserService_UpdateProfile_Call {
	_c.Call.Return(user, err)
	return _c
}

func (_c *UserService_UpdateProfile_Call) RunAndReturn(run func(ctx context.Context, meta *domain.AuditMeta, actor *domain.AuditUser, id uuid.UUID, input domain.UpdateUserInput) (*models.User, error)) *UserService_UpdateProfile_Call {
	_c.Call.Return(run)
	return _c
}
