// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package authmocks

import (
	"context"
	"time"

	"github.com/google/uuid"
	mock "github.com/stretchr/testify/mock"
)

// NewSessionRevocationStore creates a new instance of SessionRevocationStore. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewSessionRevocationStore(t interface {
	mock.TestingT
	Cleanup(func())
}) *SessionRevocationStore {
	mock := &SessionRevocationStore{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// SessionRevocationStore is an autogenerated mock type for the SessionRevocationStore type
type SessionRevocationStore struct {
	mock.Mock
}

type SessionRevocationStore_Expecter struct {
	mock *mock.Mock
}

func (_m *SessionRevocationStore) EXPECT() *SessionRevocationStore_Expecter {
	return &SessionRevocationStore_Expecter{mock: &_m.Mock}
}

// IsRevoked provides a mock function for the type SessionRevocationStore
func (_mock *SessionRevocationStore) IsRevoked(ctx context.Context, sessionID uuid.UUID) (bool, error) {
	ret := _mock.Called(ctx, sessionID)

	if len(ret) == 0 {
		panic("no return value specified for IsRevoked")
	}

	var r0 bool
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) (bool, error)); ok {
		return returnFunc(ctx, sessionID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) bool); ok {
		r0 = returnFunc(ctx, sessionID)
	} else {
		r0 = ret.Get(0).(bool)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = returnFunc(ctx, sessionID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// SessionRevocationStore_IsRevoked_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'IsRevoked'
type SessionRevocationStore_IsRevoked_Call struct {
	*mock.Call
}

// IsRevoked is a helper method to define mock.On call
//   - ctx context.Context
//   - sessionID uuid.UUID
func (_e *SessionRevocationStore_Expecter) IsRevoked(ctx interface{}, sessionID interface{}) *SessionRevocationStore_IsRevoked_Call {
	return &SessionRevocationStore_IsRevoked_Call{Call: _e.mock.On("IsRevoked", ctx, sessionID)}
}

func (_c *SessionRevocationStore_IsRevoked_Call) Run(run func(ctx context.Context, sessionID uuid.UUID)) *SessionRevocationStore_IsRevoked_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *SessionRevocationStore_IsRevoked_Call) Return(b bool, err error) *SessionRevocationStore_IsRevoked_Call {
	_c.Call.Return(b, err)
	return _c
}

func (_c *SessionRevocationStore_IsRevoked_Call) RunAndReturn(run func(ctx context.Context, sessionID uuid.UUID) (bool, error)) *SessionRevocationStore_IsRevoked_Call {
	_c.Call.Return(run)
	return _c
}

// MarkRevoked provides a mock function for the type SessionRevocationStore
func (_mock *SessionRevocationStore) MarkRevoked(ctx context.Context, sessionID uuid.UUID, expiresAt time.Time) error {
	ret := _mock.Called(ctx, sessionID, expiresAt)

	if len(ret) == 0 {
		panic("no return value specified for MarkRevoked")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, time.Time) error); ok {
		r0 = returnFunc(ctx, sessionID, expiresAt)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// SessionRevocationStore_MarkRevoked_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'MarkRevoked'
type SessionRevocationStore_MarkRevoked_Call struct {
	*mock.Call
}

// MarkRevoked is a helper method to define mock.On call
//   - ctx context.Context
//   - sessionID uuid.UUID
//   - expiresAt time.Time
func (_e *SessionRevocationStore_Expecter) MarkRevoked(ctx interface{}, sessionID interface{}, expiresAt interface{}) *SessionRevocationStore_MarkRevoked_Call {
	return &SessionRevocationStore_MarkRevoked_Call{Call: _e.mock.On("MarkRevoked", ctx, sessionID, expiresAt)}
}

func (_c *SessionRevocationStore_MarkRevoked_Call) Run(run func(ctx context.Context, sessionID uuid.UUID, expiresAt time.Time)) *SessionRevocationStore_MarkRevoked_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		var arg2 time.Time
		if args[2] != nil {
			arg2 = args[2].(time.Time)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *SessionRevocationStore_MarkRevoked_Call) Return(err error) *SessionRevocationStore_MarkRevoked_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *SessionRevocationStore_MarkRevoked_Call) RunAndReturn(run func(ctx context.Context, sessionID uuid.UUID, expiresAt time.Time) error) *SessionRevocationStore_MarkRevoked_Call {
	_c.Call.Return(run)
	return _c
}
